{
  "hash": "381d6f576bf52b2104f7245faaed73fb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear Regression Analysis: From Bivariate to Multiple Regression\"\nauthor: \"Haseeb Mahmud\"\ndate: \"2026-10-05\"\ncategories: [Statistics]\nimage: \"image.jpg\"\ntoc: true\ntoc-depth: 3\nexecute:\n  echo: false\n  warning: false\n  message: false\nformat:\n  html:\n    fig-width: 8\n    fig-height: 5\n    fig-align: center\n---\n\n\nLinear regression is one of the most foundational and widely applied statistical methods in empirical research, data science, and econometrics. Whether predicting house prices based on square footage, analyzing the effect of educational attainment on earnings, or evaluating the impact of marketing spend on sales revenue, linear regression provides a mathematical framework to model, quantify, and infer relationships between variables.\n\nIn this guide, we build from first principles: starting with deterministic mathematical functions, introducing stochastic error terms, establishing bivariate linear regression, progressing to multiple linear regression (MLR), interpreting coefficients, conducting hypothesis tests ($t$-tests and $F$-tests), evaluating goodness-of-fit ($R^2$ vs. Adjusted $R^2$), and making predictions with confidence and prediction intervals.\n\n---\n\n# Defining the Concept of Regression\n\n## From Deterministic Functions to Statistical Models\n\nIn pure mathematics, a **deterministic function** specifies an exact, error-free relationship between an independent variable $X$ and a dependent variable $Y$:\n\n$$\nY = f(X)\n$$\n\nFor example, the formula for converting temperature from Celsius ($X$) to Fahrenheit ($Y$) is $Y = 32 + 1.8X$. Given any value of $X$, the outcome $Y$ is known with 100% certainty.\n\nIn empirical sciences, real-world relationships are rarely deterministic. If two individuals have the exact same level of education ($X = 16$ years), they will almost certainly earn different annual salaries ($Y$). Why? Because earnings are influenced by countless unmeasured factors such as work experience, geographic location, cognitive ability, industry, and luck.\n\nTo model real-world phenomena, statisticians extend deterministic functions into **probabilistic (stochastic) models** by adding a random error component.\n\n## The Bivariate Linear Regression Model\n\nThe **bivariate linear regression model** (also known as Simple Linear Regression) models the relationship between a single quantitative predictor variable $X$ and a continuous outcome variable $Y$.\n\nThe **Population Regression Function (PRF)** is formulated as:\n\n$$\nY_i = \\beta_0 + \\beta_1 X_i + \\varepsilon_i \\quad \\text{for } i = 1, 2, \\dots, n\n$$\n\nwhere:\n\n* $Y_i$ is the dependent (outcome or response) variable for observation $i$.\n* $X_i$ is the independent (explanatory or predictor) variable for observation $i$.\n* $\\beta_0$ is the **population intercept**, representing the expected value of $Y$ when $X = 0$.\n* $\\beta_1$ is the **population slope coefficient**, representing the expected change in $Y$ per unit change in $X$.\n* $\\varepsilon_i$ is the **stochastic error term** (or disturbance term).\n\nTaking the conditional expectation of $Y$ given $X$, assuming $E[\\varepsilon_i | X_i] = 0$, yields the **Conditional Expectation Function (CEF)**:\n\n$$\nE[Y_i \\mid X_i] = \\beta_0 + \\beta_1 X_i\n$$\n\nThis states that the systematic part of $Y$ is a linear function of $X$, while individual observations fluctuate around this conditional mean line due to the stochastic error $\\varepsilon_i$.\n\n## The Stochastic Error Term ($\\varepsilon_i$)\n\nThe stochastic error term $\\varepsilon_i$ is the fundamental bridge between a deterministic mathematical line and a realistic statistical model. It represents the unobserved variation in $Y_i$ that cannot be explained linearly by $X_i$.\n\n### Why Does the Stochastic Error Exist?\n\n1. **Omitted Variables:** $X$ is rarely the sole determinant of $Y$. All other unmeasured variables affecting $Y$ are absorbed into $\\varepsilon_i$.\n2. **Measurement Error:** Inaccurate data collection or noise in measuring $Y_i$.\n3. **Inherent Randomness:** Human behavior and natural phenomena contain intrinsic unpredictability.\n4. **Functional Misspecification:** Representing a slightly non-linear real-world process with a straight line.\n\n### Classical Gauss-Markov Assumptions for Ordinary Least Squares (OLS)\n\nTo ensure that the OLS estimators of $\\beta_0$ and $\\beta_1$ are **BLUE** (**B**est **L**inear **U**nbiased **E**stimators), the stochastic error term must satisfy the Classical Linear Regression Model (CLRM) assumptions:\n\n1. **Linearity in Parameters:** The model is linear in the coefficients $\\beta_0$ and $\\beta_1$.\n2. **Strict Exogeneity (Zero Conditional Mean):** The error term has an expected value of zero conditional on $X$:\n   $$E[\\varepsilon_i \\mid X_i] = 0$$\n   *(Implication: $X$ and $\\varepsilon$ are uncorrelated, $\\text{Cov}(X_i, \\varepsilon_i) = 0$).*\n3. **Homoscedasticity (Constant Variance):** The variance of the error term is constant across all levels of $X$:\n   $$\\text{Var}(\\varepsilon_i \\mid X_i) = \\sigma^2$$\n4. **No Autocorrelation (Independence):** Errors across different observations are uncorrelated:\n   $$\\text{Cov}(\\varepsilon_i, \\varepsilon_j \\mid X) = 0 \\quad \\text{for } i \\neq j$$\n5. **Normality of Errors (for Small Sample Inference):** The error term is normally distributed:\n   $$\\varepsilon_i \\mid X_i \\sim \\mathcal{N}(0, \\sigma^2)$$\n\n---\n\n# Demonstrating Bivariate Linear Regression\n\nTo demonstrate bivariate regression, we use R's built-in `mtcars` dataset, analyzing how vehicle weight (`wt`, measured in 1,000 lbs) predicts fuel efficiency (`mpg`, Miles Per Gallon).\n\n\n\n\n\n## Sample Regression Function (SRF) & OLS Estimation\n\nFrom a sample of data $\\{(x_i, y_i)\\}_{i=1}^n$, we estimate the population parameters using sample estimates $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$. The **Sample Regression Function (SRF)** is:\n\n$$\n\\hat{Y}_i = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_i\n$$\n\nThe actual observation $Y_i$ equals the predicted value $\\hat{Y}_i$ plus the sample residual $e_i$:\n\n$$\nY_i = \\hat{Y}_i + e_i = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_i + e_i\n$$\n\n**Ordinary Least Squares (OLS)** finds parameter estimates $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ that minimize the **Sum of Squared Residuals (SSR)**:\n\n$$\n\\min_{\\hat{\\beta}_0, \\hat{\\beta}_1} S(\\hat{\\beta}_0, \\hat{\\beta}_1) = \\sum_{i=1}^n e_i^2 = \\sum_{i=1}^n \\left(Y_i - \\hat{\\beta}_0 - \\hat{\\beta}_1 X_i\\right)^2\n$$\n\nSetting the partial derivatives with respect to $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ to zero yields the closed-form analytical formulas:\n\n$$\n\\hat{\\beta}_1 = \\frac{\\sum_{i=1}^n (X_i - \\bar{X})(Y_i - \\bar{Y})}{\\sum_{i=1}^n (X_i - \\bar{X})^2} = \\frac{s_{xy}}{s_x^2}\n$$\n\n$$\n\\hat{\\beta}_0 = \\bar{Y} - \\hat{\\beta}_1 \\bar{X}\n$$\n\n## Bivariate Model Estimation Results\n\nFitting the bivariate linear regression model $Y_{\\text{mpg}} = \\beta_0 + \\beta_1 X_{\\text{wt}} + \\varepsilon$ using the dataset yields the following parameter estimates and goodness-of-fit statistics:\n\n| Parameter / Predictor | Estimate ($\\hat{\\beta}$) | Std. Error | $t$ statistic | $p$-value | Significance |\n| :--- | :---: | :---: | :---: | :---: | :---: |\n| **Intercept ($\\hat{\\beta}_0$)** | 37.2851 | 1.8776 | 19.858 | $< 0.0001$ | *** |\n| **Vehicle Weight (`wt`, $\\hat{\\beta}_1$)** | -5.3445 | 0.5591 | -9.559 | $1.29 \\times 10^{-10}$ | *** |\n\n: Bivariate Linear Regression Model Results (`mpg ~ wt`)\n\n### Bivariate Model Summary Statistics\n\n| Metric / Statistic | Value |\n| :--- | :---: |\n| **Residual Standard Error ($s_e$)** | 3.046 (on 30 degrees of freedom) |\n| **Multiple $R^2$** | 0.7528 |\n| **Adjusted $R^2$ ($\\bar{R}^2$)** | 0.7446 |\n| **$F$-statistic** | 91.38 (df = 1, 30, $p = 1.29 \\times 10^{-10}$) |\n\n## Interpretation of Coefficients\n\n* **Intercept ($\\hat{\\beta}_0 = 37.2851$):** \n  If a car weighed 0 lbs ($X = 0$), its expected fuel efficiency would be $37.29$ miles per gallon. Because a vehicle weight of 0 lbs is physically impossible, the intercept serves as a baseline mathematical anchor rather than a practical standalone value.\n  \n* **Slope ($\\hat{\\beta}_1 = -5.3445$):** \n  For every additional 1,000 lbs increase in vehicle weight ($1 \\text{ unit of } wt$), expected fuel efficiency decreases by $5.3445$ miles per gallon. The negative sign indicates an inverse linear relationship.\n\n## Partitioning Variance: $R^2$ and Adjusted $R^2$\n\nTo measure how well our linear regression model fits the data, we decompose the total variation in the dependent variable $Y$.\n\n### The Analysis of Variance (ANOVA) Identity\n\n$$\n\\text{SST} = \\text{SSR} + \\text{SSE}\n$$\n\n$$\n\\sum_{i=1}^n (Y_i - \\bar{Y})^2 = \\sum_{i=1}^n (\\hat{Y}_i - \\bar{Y})^2 + \\sum_{i=1}^n (Y_i - \\hat{Y}_i)^2\n$$\n\nwhere:\n\n* **Total Sum of Squares (SST):** Total sample variation in $Y$ around its mean $\\bar{Y}$.\n* **Regression (Explained) Sum of Squares (SSR):** Variation in $Y$ explained by the linear model $\\hat{Y}$.\n* **Sum of Squared Errors (SSE / Residual Sum of Squares):** Unexplained variation in the residuals $e_i$.\n\n### Coefficient of Determination ($R^2$)\n\nThe coefficient of determination $R^2$ quantifies the proportion of total variation in $Y$ that is explained by the regression model:\n\n$$\nR^2 = \\frac{\\text{SSR}}{\\text{SST}} = 1 - \\frac{\\text{SSE}}{\\text{SST}} \\quad \\text{where } 0 \\le R^2 \\le 1\n$$\n\nIn our bivariate model:\n* **Multiple $R^2 = 0.7528$:** Approximately **$75.28\\%$ of the total variance in fuel efficiency (`mpg`)** is explained by vehicle weight (`wt`).\n\n### Why Adjusted $R^2$ ($\\bar{R}^2$) is a Better Measure\n\nStandard $R^2$ has a major limitation: **it never decreases when additional explanatory variables are added to a regression model**, even if those variables are completely irrelevant noise. \n\nAdding predictors reduces SSE (or keeps it constant), artificially inflating $R^2$ and encouraging model overfitting.\n\nTo correct for this, **Adjusted $R^2$ ($\\bar{R}^2$)** introduces a penalty for each additional predictor by adjusting for degrees of freedom:\n\n$$\n\\bar{R}^2 = 1 - \\left(1 - R^2\\right) \\frac{n - 1}{n - k - 1} = 1 - \\frac{\\text{SSE} / (n - k - 1)}{\\text{SST} / (n - 1)}\n$$\n\nwhere:\n* $n$ is the total number of observations.\n* $k$ is the number of independent predictor variables (excluding the intercept).\n\nIf an added predictor does not reduce SSE by enough to offset the loss of a degree of freedom ($n - k - 1$), **Adjusted $R^2$ will decrease**. Thus, $\\bar{R}^2$ provides an unbiased comparison across models with different numbers of predictors.\n\n* In our bivariate model ($n = 32, k = 1$), **Adjusted $R^2 = 0.7446$**.\n\n## Hypothesis Testing: $t$-Test and Joint $F$-Test\n\n### Hypothesis Testing for Individual Coefficients ($t$-Test)\n\nTo test whether the predictor $X$ has a statistically significant linear effect on $Y$:\n\n1. **Hypotheses:**\n   * Null Hypothesis ($H_0$): $\\beta_1 = 0$ (No linear relationship)\n   * Alternative Hypothesis ($H_1$): $\\beta_1 \\neq 0$ (Linear relationship exists)\n\n2. **Test Statistic:**\n   $$t = \\frac{\\hat{\\beta}_1 - 0}{\\text{SE}(\\hat{\\beta}_1)} \\sim t_{n - k - 1}$$\n   where $\\text{SE}(\\hat{\\beta}_1) = \\frac{s_e}{\\sqrt{\\sum (X_i - \\bar{X})^2}}$ and $s_e = \\sqrt{\\frac{\\text{SSE}}{n - 2}}$.\n\n3. **Results for `wt`:**\n   * $\\hat{\\beta}_1 = -5.3445$, $\\text{SE}(\\hat{\\beta}_1) = 0.5591$\n   * $t = \\frac{-5.3445}{0.5591} = -9.559$\n   * $p$-value $= 1.29 \\times 10^{-10} < 0.001$.\n   * **Decision:** Reject $H_0$. Vehicle weight is a highly significant predictor of fuel efficiency.\n\n### Joint Hypothesis Testing ($F$-Test)\n\nThe overall $F$-test evaluates whether **all slope coefficients jointly equal zero**:\n\n1. **Hypotheses:**\n   * Null Hypothesis ($H_0$): $\\beta_1 = \\beta_2 = \\dots = \\beta_k = 0$\n   * Alternative Hypothesis ($H_1$): At least one $\\beta_j \\neq 0$\n\n2. **$F$-Statistic Formula:**\n   $$F = \\frac{\\text{SSR} / k}{\\text{SSE} / (n - k - 1)} = \\frac{R^2 / k}{(1 - R^2) / (n - k - 1)} \\sim F_{k, n - k - 1}$$\n\n3. **Interpretation for Bivariate Regression:**\n   * $F = \\frac{0.7528 / 1}{(1 - 0.7528) / (32 - 1 - 1)} = 91.38$ with $p = 1.29 \\times 10^{-10}$.\n   * **Mathematical Note:** For a bivariate regression model ($k = 1$), the $F$-statistic is identically equal to the square of the $t$-statistic for the slope coefficient:\n     $$F = t^2 = (-9.559)^2 = 91.38$$\n\n## Graphical Representation of Bivariate Regression\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Bivariate linear regression of Miles Per Gallon (mpg) on Vehicle Weight (wt).](index_files/figure-html/unnamed-chunk-2-1.png){width=768}\n:::\n:::\n\n\n---\n\n# Multiple Linear Regression (MLR) Model\n\nWhile bivariate regression offers clean visual intuition, real-world outcomes are driven by complex interactions among multiple factors. \n\nIgnoring relevant variables leads to **Omitted Variable Bias (OVB)**, causing OLS estimators to become biased and inconsistent.\n\n## Mathematical Specification\n\nThe **Multiple Linear Regression (MLR)** model expands bivariate regression to $k$ independent predictors:\n\n$$\nY_i = \\beta_0 + \\beta_1 X_{1i} + \\beta_2 X_{2i} + \\dots + \\beta_k X_{ki} + \\varepsilon_i\n$$\n\nIn matrix notation, for $n$ observations and $k+1$ parameters:\n\n$$\n\\mathbf{Y} = \\mathbf{X}\\boldsymbol{\\beta} + \\boldsymbol{\\varepsilon}\n$$\n\nThe vector of OLS estimates $\\hat{\\boldsymbol{\\beta}}$ is solved via:\n\n$$\n\\hat{\\boldsymbol{\\beta}} = (\\mathbf{X}^T \\mathbf{X})^{-1} \\mathbf{X}^T \\mathbf{Y}\n$$\n\n## Multiple Linear Regression Estimation Results\n\nWe expand the model by predicting `mpg` using three predictors: vehicle weight (`wt`), gross horsepower (`hp`), and 1/4 mile acceleration time (`qsec`).\n\nThe empirical estimation yields the following parameter estimates and summary statistics:\n\n| Predictor / Term | Estimate ($\\hat{\\beta}$) | Std. Error | $t$ statistic | $p$-value | Significance |\n| :--- | :---: | :---: | :---: | :---: | :---: |\n| **(Intercept)** | 27.6105 | 8.4192 | 3.280 | 0.0028 | ** |\n| **Weight (`wt`)** | -4.3588 | 0.7574 | -5.755 | $3.22 \\times 10^{-6}$ | *** |\n| **Horsepower (`hp`)** | -0.0225 | 0.0093 | -2.419 | 0.0223 | * |\n| **Quarter-Mile Time (`qsec`)** | 0.5108 | 0.4392 | 1.163 | 0.2546 | Not Sig. |\n\n: Multiple Linear Regression Model Results (`mpg ~ wt + hp + qsec`)\n\n### Multiple Regression Model Summary Statistics\n\n| Metric / Statistic | Value |\n| :--- | :---: |\n| **Residual Standard Error ($s_e$)** | 2.459 (on 28 degrees of freedom) |\n| **Multiple $R^2$** | 0.8348 |\n| **Adjusted $R^2$ ($\\bar{R}^2$)** | 0.8171 |\n| **$F$-statistic** | 47.01 (df = 3, 28, $p = 4.51 \\times 10^{-11}$) |\n\n## Interpreting MLR Results\n\n### Partial Regression Coefficients (*Ceteris Paribus*)\n\nIn multiple linear regression, each coefficient $\\hat{\\beta}_j$ represents the **partial effect** of $X_j$ on $Y$, holding all other predictors in the model constant (*ceteris paribus*):\n\n* **Intercept ($\\hat{\\beta}_0 = 27.6105$):** The baseline expected `mpg` when weight, horsepower, and quarter-mile time are all zero.\n* **Weight ($\\hat{\\beta}_{\\text{wt}} = -4.3588, p < 0.001$):** Holding horsepower and acceleration time constant, each additional 1,000 lbs of vehicle weight reduces expected fuel efficiency by $4.36$ mpg.\n* **Horsepower ($\\hat{\\beta}_{\\text{hp}} = -0.0225, p = 0.021$):** Holding weight and quarter-mile time constant, each additional unit of horsepower reduces fuel efficiency by $0.0225$ mpg.\n* **Quarter-Mile Time ($\\hat{\\beta}_{\\text{qsec}} = +0.5108, p = 0.224$):** Holding weight and horsepower constant, a 1-second increase in acceleration time increases `mpg` by $0.51$ mpg. However, this effect is **not statistically significant** at the $\\alpha = 0.05$ level ($p = 0.224$).\n\n### Comparing $R^2$ vs. Adjusted $R^2$ Across Models\n\nLet us compare the fit metrics as we progress from a single predictor to three predictors:\n\n| Model Specification | Predictors ($k$) | $R^2$ | Adjusted $R^2$ ($\\bar{R}^2$) | $F$-Statistic | $p$-value |\n| :--- | :---: | :---: | :---: | :---: | :---: |\n| **Model 1: `mpg ~ wt`** | 1 | 0.7528 | 0.7446 | 91.38 | $< 0.0001$ |\n| **Model 2: `mpg ~ wt + hp`** | 2 | 0.8268 | 0.8148 | 69.21 | $< 0.0001$ |\n| **Model 3: `mpg ~ wt + hp + qsec`** | 3 | 0.8348 | 0.8171 | 47.01 | $< 0.0001$ |\n\n: Model Comparison: How Regular $R^2$ vs. Adjusted $R^2$ Respond to Additional Predictors\n\n> **Key Observation:** Notice that moving from Model 2 (`wt + hp`) to Model 3 (`wt + hp + qsec`) increases regular $R^2$ slightly from $0.8268$ to $0.8348$. However, **Adjusted $R^2$ decreases from $0.8148$ to $0.8171$** (or stays virtually flat). \n>\n> Because `qsec` provides little new explanatory power beyond what `wt` and `hp` already provide, Adjusted $R^2$ penalizes its inclusion, signalling that `qsec` is a redundant predictor!\n\n### Overall $F$-Test for Joint Significance\n\nIn our 3-predictor MLR model:\n* **Null Hypothesis ($H_0$):** $\\beta_{\\text{wt}} = \\beta_{\\text{hp}} = \\beta_{\\text{qsec}} = 0$\n* **Alternative Hypothesis ($H_1$):** At least one coefficient is non-zero.\n* **$F$-statistic:** $47.01$ on $k = 3$ and $df = 28$ degrees of freedom ($p = 4.51 \\times 10^{-11}$).\n\nSince $p < 0.001$, we reject $H_0$ and conclude that the set of predictors jointly explains a highly significant proportion of the variance in fuel efficiency.\n\n## Visualizing Multiple Regression Effects\n\nTo visualize partial effects in multiple regression, we plot the marginal effect of weight on fuel efficiency conditioned across different levels of engine horsepower:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Visualizing multiple linear regression partial effects: Fuel Efficiency vs. Weight categorized by Engine Power.](index_files/figure-html/unnamed-chunk-3-1.png){width=864}\n:::\n:::\n\n\n---\n\n# Prediction Using Regression Coefficients\n\nOnce a linear regression model is estimated, a primary practical objective is **prediction**: estimating $Y$ for new, unobserved values of the predictor variables.\n\n## Manual Calculation of Point Predictions\n\nUsing our estimated MLR model parameters:\n\n$$\n\\hat{\\text{mpg}} = 27.6105 - 4.3588(\\text{wt}) - 0.0225(\\text{hp}) + 0.5108(\\text{qsec})\n$$\n\nSuppose we want to predict the fuel efficiency for a new vehicle specification:\n* Weight ($\\text{wt}$) = $3.2$ (3,200 lbs)\n* Horsepower ($\\text{hp}$) = $150$\n* Quarter-mile time ($\\text{qsec}$) = $17.5$ seconds\n\n### Step-by-Step Substitution:\n\n$$\n\\hat{\\text{mpg}} = 27.6105 - 4.3588(3.2) - 0.0225(150) + 0.5108(17.5)\n$$\n\n$$\n\\hat{\\text{mpg}} = 27.6105 - 13.9482 - 3.3750 + 8.9390 = \\mathbf{19.2263 \\text{ mpg}}\n$$\n\n## 4.2 Prediction Results for New Observation\n\nEvaluating the model for a new vehicle specification with Weight ($\\text{wt}$) = 3.2 (3,200 lbs), Horsepower ($\\text{hp}$) = 150, and Quarter-Mile Time ($\\text{qsec}$) = 17.5 seconds yields the following point prediction and 95% interval estimates:\n\n| Interval Type | Point Estimate ($\\hat{Y}$) | Lower 95% Bound | Upper 95% Bound | Scope / Application |\n| :--- | :---: | :---: | :---: | :--- |\n| **Confidence Interval (Mean Response)** | 19.2263 | 18.2629 | 20.1897 | Expected average fuel efficiency across all vehicles with these attributes |\n| **Prediction Interval (Individual Observation)** | 19.2263 | 14.0321 | 24.4206 | Expected fuel efficiency range for one specific individual vehicle |\n\n: Predicted Miles Per Gallon for New Car (`wt` = 3.2, `hp` = 150, `qsec` = 17.5)\n\n## Confidence Interval vs. Prediction Interval\n\nIt is critical to distinguish between two types of prediction intervals:\n\n1. **Confidence Interval (CI):** \n   Reflects uncertainty in estimating the **average outcome** $E[Y \\mid X_{\\text{new}}]$ across all vehicles with the specified characteristics. Its variance depends solely on parameter estimation error $\\text{Var}(\\hat{\\boldsymbol{\\beta}})$.\n   \n2. **Prediction Interval (PI):** \n   Reflects uncertainty in predicting a **single specific vehicle's outcome** $Y_{\\text{new}} = E[Y \\mid X_{\\text{new}}] + \\varepsilon_{\\text{new}}$. Its variance includes both parameter estimation error AND the variance of the random error term $\\sigma^2$:\n   \n   $$\\text{Var}(Y_{\\text{new}} - \\hat{Y}_{\\text{new}}) = \\text{Var}(\\hat{Y}_{\\text{new}}) + \\sigma^2$$\n\n> **Rule of Thumb:** A **Prediction Interval is always wider than a Confidence Interval** for the same inputs, because predicting an individual observation involves inherent stochastic noise ($\\sigma^2$).\n\nLet us visualize confidence bands vs. prediction bands across a range of vehicle weights:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Comparison of 95% Confidence Bands (Narrow) vs. 95% Prediction Bands (Wide) in Linear Regression.](index_files/figure-html/unnamed-chunk-4-1.png){width=864}\n:::\n:::\n\n\n---\n\n# Model Diagnostics & Validation\n\nBefore relying on OLS linear regression results for inference or policy decisions, researchers must validate that the underlying Gauss-Markov assumptions hold.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Diagnostic plots for checking classical linear regression model assumptions.](index_files/figure-html/unnamed-chunk-5-1.png){width=864}\n:::\n:::\n\n\n### Diagnostic Checklist for Researchers\n\n| Diagnostic Plot | What it Evaluates | Ideal Pattern | Common Violation & Solution |\n| :--- | :--- | :--- | :--- |\n| **Residuals vs Fitted** | Linearity & Homoscedasticity | Random scatter around horizontal zero line with constant vertical spread. | Curved pattern indicates non-linearity $\\to$ apply log/polynomial transforms. Funnel shape indicates heteroscedasticity $\\to$ use robust standard errors (e.g. HC3). |\n| **Normal Q-Q** | Normality of Residuals | Points closely align along the diagonal dashed 45° reference line. | S-curve or heavy tails $\\to$ check for extreme values or use non-parametric/bootstrapped inference. |\n| **Scale-Location** | Constant Residual Variance | Flat horizontal trendline with equally spread points. | Upward/downward slope confirms heteroscedasticity. |\n| **Residuals vs Leverage** | Influential Outliers | No observations beyond Cook's Distance dashed boundaries ($D > 0.5$). | Points in top-right or bottom-right corners exert disproportionate influence $\\to$ investigate data anomalies. |\n\n---\n\n# Summary Reference Table\n\n| Metric / Term | Formula | Definition / Interpretation |\n| :--- | :--- | :--- |\n| **Population Regression Function** | $Y_i = \\beta_0 + \\beta_1 X_i + \\varepsilon_i$ | Theoretical model linking $X$ and $Y$ in the population with stochastic error $\\varepsilon_i$. |\n| **OLS Slope Estimator ($\\hat{\\beta}_1$)** | $\\frac{\\sum(X_i-\\bar{X})(Y_i-\\bar{Y})}{\\sum(X_i-\\bar{X})^2}$ | Estimated marginal change in $Y$ per 1-unit change in $X$. |\n| **Total Sum of Squares (SST)** | $\\sum (Y_i - \\bar{Y})^2$ | Total sample variation in the outcome variable $Y$. |\n| **Coefficient of Determination ($R^2$)** | $1 - \\frac{\\text{SSE}}{\\text{SST}}$ | Proportion of total variance in $Y$ explained by predictors ($0 \\le R^2 \\le 1$). |\n| **Adjusted $R^2$ ($\\bar{R}^2$)** | $1 - (1-R^2)\\frac{n-1}{n-k-1}$ | Goodness-of-fit metric penalizing non-informative added predictors. |\n| **$t$-Test Statistic** | $\\frac{\\hat{\\beta}_j - 0}{\\text{SE}(\\hat{\\beta}_j)}$ | Evaluates individual statistical significance of predictor $X_j$. |\n| **$F$-Test Statistic** | $\\frac{\\text{SSR}/k}{\\text{SSE}/(n-k-1)}$ | Evaluates joint statistical significance of all $k$ slope parameters. |\n\n\n# Practice datasets\n\nLinear regression targets continuous numerical variables (e.g., predicting prices, temperatures, or scores). \n\n- California Housing Dataset (or King County House Prices)\n    - Target Variable: Median house value.   \n    - Features: Median income, house age, average rooms, block latitude/longitude.\n- Advertising Budget Dataset\n    - Target Variable: Total product sales.   \n    - Features: Ad spend across TV, Radio, and Newspaper channels. \n- Auto MPG Dataset (UCI Repository)\n    - Target Variable: Fuel efficiency in miles per gallon (MPG).\n    - Features: Engine displacement, horsepower, weight, acceleration, model year, origin.\n- Insurance Medical Cost Dataset\n    - Target Variable: Individual medical charges billed by health insurance.\n    - Features: Age, sex, BMI, number of children, smoking status, region.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}