{
  "hash": "4c208596e5fbfec82f55b7c6ca213435",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Descriptive Statistics\"\nauthor: \"Haseeb Mahmud\"\ndate: \"2026-09-30\"\ncategories: [Statistics]\nimage: \"image.jpg\"\ntoc: true\ntoc-depth: 3\nexecute:\n  warning: false\n  message: false\nformat:\n  html:\n    code-fold: false\n    fig-width: 8\n    fig-height: 7\n    fig-align: center\n---\n\n\n# Measures of central Tendency\n\n## Arithmetic mean\n\nThe arithmetic mean, or mean of a set of measurements is defined to be the sum of measurements divided by the total number of measurements.\n\nUsually, the population mean is denoted by $\\mu$ and the sample mean is denoted by $\\bar{y}$. The sample mean of a series is defined as,\n\n$$\n\\bar{y}=\\frac{\\sum_iY_i}{n}\n$$\n\nwhere, $n$ is the number of observations.\n\nExample A sample of $n=15$ overdue accounts in a large department store yields the following amounts due,\n\n|       |        |        |\n|-------|--------|--------|\n| 55.2  | 4.88   | 271.95 |\n| 18.06 | 180.29 | 365.29 |\n| 28.16 | 399.11 | 807.8  |\n| 44.14 | 97.47  | 9.98   |\n| 61.61 | 56.89  | 82.73  |\n\nThe sample mean is computed as follows,\n\n$$\n\\bar{y}= \\frac{\\sum_iY_i}{n}=\\frac{55.20+18.06+ .... + 82.73}{15}=\\frac{2483.56}{15}=165.57\n$$\n\n### Some comments about the arithmetic mean\n\n- It is the most common central tendency measure\n- There exist only one mean of a dataset/series\n- The value of the mean is influenced by the extreme values. Trimming or deleting extreme observations helps to reduce/omit that influence\n- Means of samples from a single population can be combined to get the population mean.\n- It is applicable to quantitative data only.\n\n## Median\n\nThe median of a set of measurements is defined to be the middle value when the measurements are arranged from lowest to highest. So, first we need to sort the dataset from lowest to highest.\n\n$$\ny_1 \\leq y_2 \\leq y_3 \\leq .... \\leq y_i \\leq .. \\leq y_n\n$$\n\nThen, the median of a series will be,\n\n- $\\frac{N+1}{2}$-th observation if $n$ is odd.\n- Average of $\\left(\\frac{N}{2}\\right)$ and $\\left(\\frac{N}{2}+1\\right)$-th observation if $n$ is even.\n\n### Median: some comments\n\n- It is the central value, 50 percent of the observations lie above it and the rest fall below it.\n- There is only one median in a dataset\n- It is not affected by extreme observations\n- Medians of subsamples cannot be combined to get the median of the population.\n- It is applicable to quantitative data only\n- For group data, its value is rather stable even when the data are organized into different categories.\n\n## Mode\n\nA mode of a set of measurements is defined to be the measurement that occurs most often, i.e. the highest frequency.\n\n### Mode: some comments\n\nThere can be more than one mode in a dataseries. Modes of the subsamples cann't be used to determine to formulate the mode of the population It is applicable for both qualitative and quantitative data For grouped data, its value can change depending on the categories used.\n\n## Relationship: mean, Median, Mode\n\n- When a variable is normally distributed, the mean, median, and mode are the same number.\n- When the variable is skewed to the left (i.e., negatively skewed), the mean shifts to the left the most, the median shifts to the left the second most, and the mode the least affected by the presence of skew in the data.\n- When the variable is skewed to the right (i.e., positively skewed), the mean is shifted to the right the most, the median is shifted to the right the second most, and the mode the least affected.\n\n![Relationship among different central tendency measures](2_1.png)\n\n# Measures of dispersion\n\n## Range\n\nThe range of a set of measurements is defined to be the difference between the largest and the smallest measurements of the set.\n\nFrom the above dataset we are working on, the smallest values is 4.88 and the largest is 807.80. The range of the data would be,\n\n$$\nrange = 807.80 - 4.88 = 802.92\n$$\n\n## Variance and standard deviation\n\nThe *variance* of a set of measurements $y_1, y_2, y_3, .... , y_n$, with a mean of $\\bar{y}_n$ is the sum of the squared deviations divided by $n-1$. Symbolically,\n\n$$\ns^2 = \\frac{\\sum_{i=1}^n(x_i-\\bar{x})^2}{n-1}\n$$\n\nWe are assuming, we are working with **samples**. In case of \\textit{population} variance we will replace $n-1$ with $n$ in the denominator. Sample variance is denoted by $s^2$ and the population variance is denoted by $\\sigma^2$.\n\nSample variance is an *unbiased estimator* of the population variance. That means, if we take different sub-samples from the population, then the average variance of those samples are (roughly) equal to the population variance.\n\nThe **standard deviation** is a set of measurements is defined to be the positive square root of the variance. $$\ns = \\sqrt{\\frac{\\sum_{i=1}^n(x_i-\\bar{x})^2}{n-1}}\n$$\n\nAs mentioned before, sample standard deviation will be denoted by $s$ and the population standard deviation is denoted by $\\sigma$. In real life, this difference is often ignored.\n\n### Variance and standard deviation: Example\n\n| Product | Calories |\n|------------------------------------|------------------------------------|\n| Dunkin's Donuts Iced Mocha Swirl latte (whole milk) | 240 |\n| Starbucks coffee frappuccino blended coffee | 260 |\n| Dunkin Donuts coffee coolatta | 350 |\n| Starbucks Iced Coffee Mocha Espresso (whole Milk and whipped cream | 350 |\n| Starbucks Mocha Flappuccino blended coffee (whipped cream) | 420 |\n| Starbucks Chocolate Brownie Flappuccino blended coffee (whipped cream) | 510 |\n| Starbucks Chocolate Flappuccino blended creme (whipped cream | 530 |\n\n: Calories in different Starbucks drinks\n\nTo calculate standard deviation and variance first we need to calculate the mean, then the squared differences\n\n$$\n\\bar{x} = \\frac{\\sum_{i=1}^nX_i}{n} = \\frac{2660}{7} = 380\n$$\n\n| Calories | $(x_i - \\bar{x})$ | $(x_i - \\bar{x})^2$ |\n|----------|-------------------|---------------------|\n| 240      | -140              | 19600               |\n| 260      | -120              | 14400               |\n| 350      | -30               | 900                 |\n| 350      | -30               | 900                 |\n| 420      | 40                | 1600                |\n| 510      | 130               | 16900               |\n| 530      | 150               | 22500               |\n|          |                   | 76800               |\n\nPutting all into the formula, we can get the variance.\n\n$$\ns^2 = \\frac{\\sum_{i=1}^n(x_i-\\bar{x})^2}{n-1} = \\frac{76800}{6} =  12800 \n$$\\\nAnd, the standard deviation is,\n\n$$\ns = \\sqrt{s^2} = \\sqrt{12800} = 113.1371\n$$\n\n### Characteristics of deviation measures\n\n- The greater the spread or dispersion of the data, the larger the range, $\\sigma^2$ and $\\sigma$.\n- The greater the concentration of the data around the central value, the smaller the range, $\\sigma^2$ and $\\sigma$.\n- If the values are all the same (so that there are no variation in the data), the range, $\\sigma^2$ and $\\sigma$ will all equal to zero.\n- None of the measures of variation can *ever* be negative.\n\n## The coefficient of variation\n\nUnlike the range, $\\sigma$ and $\\sigma^2$, the coefficient of variation is a relative measure expressed as a percentage rather than units of a particular data. The coefficient of variation is equal to the standard deviation by the mean, multiplied by $100\\%$.\n\n$$\nCV = \\left(\\frac{\\sigma}{\\bar{x}}\\right)\\times 100\\%\n$$\n\nThe coefficient of variation is particularly useful to compare the variability of two different datasets measured in two different units of measurements.\n\nFrom the previous Starbucks data, the coefficient of variation can be calculated as,\n\n$$\nCV = \\left(\\frac{s}{\\bar{x}}\\right)\\times 100\\% = \\frac{113.1371}{380} \\times 100\\% = 28.79\\%\n$$\n\n# Confidence Intervals\n\nThe goal here is to estimate the sample information to estimate the population parameter of interest to assess the reliability of the estimate.\n\n- The unknown population parameter (e.g. mean or proportion) that we are interested in estimating is called *target parameter*}.\n- A *point estimator* of a population is a rule or formula that tells us how to use the sample data to calculate as single number that can be used as an estimate of the target parameter.\n- An *interval estimator or confidence interval* is a formula that tells us how to use the sample data to calculate an interval that estimates the target parameter.\n\n## Confidence interval: large sample\n\n**CI for a** $\\mu$: Normal $z$-statistic\n\nLet $x_1, x_2, ... , x_n$ be a random sample of $n$ observations from a normally distributed population with unknown mean $\\mu$ and known $\\sigma^2$. Suppose that, we want a $100(1-\\alpha)\\%$ CI of the population mean. Previously, we saw that,\n\n$$\nz = \\frac{\\bar{x}-\\mu}{\\sigma/\\sqrt{n}}\n$$\n\nhas a $N(0,1)$ distribution and $z_{\\alpha/2}$ is the value from the $N(0,1)$ such that the upper tail probability is $\\alpha/2$. We use the basis algebra to find,\n\n$$\n1 - \\alpha =  \\mathbb{P} (-z_{\\alpha/2} < z < z_{\\alpha/2}) = \\mathbb{P} \\left(-z_{\\alpha/2} < \\frac{\\bar{x}-\\mu}{\\sigma/\\sqrt{n}} < z_{\\alpha/2}\\right)\n$$\n\nwhich in turn,\n\n$$\n\\mathbb{P} \\left(-z_{\\alpha/2} \\frac{\\sigma}{\\sqrt{n}} < \\bar{x} - \\mu < z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}\\right)\n= \\mathbb{P} \\left(\\bar{x}-z_{\\alpha/2} \\frac{\\sigma}{\\sqrt{n}} < \\mu < \\bar{x}+z_{\\alpha/2}\\frac{\\sigma}{\\sqrt{n}}\\right)\n$$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n\n## Central limit theorem\n\nAccording to the Central Limit Theorem the sampling distribution of the sample mean is approximately normal for large samples. For a $95\\%$ confidence level it follows that,\n\n$$\n\\mathbb{P} \\left(\\bar{x}-1.96 \\frac{\\sigma}{\\sqrt{n}} < \\mu < \\bar{x}+1.96\\frac{\\sigma}{\\sqrt{n}}\\right)\n$$\n\nThe interval $\\bar{x} \\pm 1.96\\sigma_{\\bar{x}}$ is called the large sample $95\\%$ confidence interval for the population mean $\\mu$. The term large sample refers to the sample being of sufficiently large size that we can apply the Central Limit Theory and the normal $z$ statistic to determine the form of the sampling distribution of $\\bar{x}$. Empirical research suggests that a sample size $n$ exceeding a value between 20 and 30 will usually yield a sampling distribution of $\\bar{x}$, that is normal.\n\nIf the sample means (e.g. $\\bar{x}_1, \\bar{x}_3$ and $\\bar{x}_4$) falls between the two lines on either side of $\\mu$, then the interval $\\bar{x} \\pm 1.96\\sigma_{\\bar{x}}$ will contain $\\mu$; if $\\bar{x}$ falls outside the boundaries (e.g. $\\bar{x}_2$), the interval $\\bar{x} \\pm 1.96\\sigma_{\\bar{x}}$ will not contain $\\mu$.\\\\ \\vspace{0.2cm} From the Empirical rule, we know that, the area under the normal curve (the sampling distribution of $\\bar{x}$ between these boundaries is exactly 0.95. Thus the probability that a randomly selected interval $\\bar{x} \\pm 1.96\\sigma_{\\bar{x}}$, will contain $\\mu$ is equal to $0.95$ or $95\\%$.\\\\ \\vspace{0.2cm} Large sample interval estimator requires knowing the value of the population $\\sigma$. In most practical applications, the value of population $\\sigma$ is unknown. For large samples, in the absence of $\\sigma$, sample standard deviation $s$ provides a good approximation to $\\sigma$.\n\n# Covariance and correlation\n\nCovariance is a measure of the relationship between two random variables. The metric evaluates how much - to what extent - the variables change together. In other words, it is essentially a measure of the variance between two variables. However, the metric does not assess the dependency between variables.\n\n$$\nCov (x, y) = \\frac{\\sum(x_i - \\bar{x})(y_i - \\bar{y})}{n}\n$$\n\nFor a sample covariance, we need to deduct 1 from the demoninator, i.e. $(n-1)$.\n\n- Positive covariance: Indicates that two variables tend to move in the same direction.\n- Negative covariance: Reveals that two variables tend to move in inverse directions.\n\nUsing covariance, we can only gauge the direction of the relationship (whether the variables tend to move in tandem or show an inverse relationship). However, it does not indicate the strength of the relationship, nor the dependency between the variables.\n\nCorrelation measures the strength of the relationship between variables. Correlation is the scaled measure of covariance. It is dimensionless. In other words, the correlation coefficient is always a pure value and not measured in any units.\n\n$$\n\\rho = \\frac{cov(x, y)}{\\sigma_x \\sigma_y}\n$$\n\n- Correlation value ranges from $-1$ to $+1$. The correlation of zero indicates zero relationship.\n- $\\rho_{x,y} = \\rho_{y,x}$\n- The correlation is not synonimous to causation!\n- More on this topic will be covered later in the degree program.\n\n## Percentiles\n\nThe $p$-th percentile of a set of $n$-measurements arranged in order of magnitude is that value that has at most $p\\%$ of the measurements below it and at most $(100-p)\\%$ above it.\n\nPercentiles are frequently used to describe the results of achievements test scores and the ranking of a person in comparison to the rest of the people taking the examination. Specific percentile of interest are the 25th, 50th and 75th percentiles; often called the lower quantile, the middle quantile (median) and the upper quantile respectively. Similarly, if we divide the data by 10 parts then we refer every part as *deciles*.\n\n## 3. Skewness and Kurtosis\n\n**Skewness** measures the asymmetry of a probability distribution around its mean:\n\n- **Zero Skewness:** Symmetric distribution, where mean, median, and mode coincide (e.g., standard normal distribution).\n\n- **Positive (Right) Skewness:** Long tail extending to the right ($\\text{mode} \\le \\text{median} \\le \\text{mean}$).\n\n- **Negative (Left) Skewness:** Long tail extending to the left ($\\text{mean} \\le \\text{median} \\le \\text{mode}$).\n\n**Kurtosis** measures the tail heaviness and peakedness relative to a normal distribution:\n\n- **Mesokurtic (Normal):** Excess kurtosis $\\approx 0$ (Standard Kurtosis $= 3$).\n\n- **Leptokurtic (Heavy-tailed / High Peak):** Excess kurtosis $> 0$; higher probability of extreme values or outliers.\n\n- **Platykurtic (Light-tailed / Flat Peak):** Excess kurtosis $< 0$; fewer extreme outliers.\n\n### Visualizing Skewness & Kurtosis Impact\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n### Assessing Normality via Skewness and Kurtosis\n\nTo determine whether data is normally distributed based on sample skewness and excess kurtosis:\n\n1. **Rules of Thumb for Acceptable Normality**\n\n   - **Skewness:** Values between $-0.5$ and $+0.5$ indicate near symmetry; values between $-1.0$ and $+1.0$ are generally acceptable for parametric statistics.\n   - **Excess Kurtosis:** Values between $-1.0$ and $+1.0$ indicate a near-normal tail structure.\n\n2. **Standardized Z-Score Method**\n\n   Calculate $Z$-scores for skewness ($Z_{\\text{skew}}$) and kurtosis ($Z_{\\text{kurt}}$):\n   $$Z_{\\text{skew}} = \\frac{\\text{Skewness}}{\\text{SE}_{\\text{skew}}}$$\n   Where $\\text{SE}_{\\text{skew}} \\approx \\sqrt{\\frac{6}{N}}$. If $|Z_{\\text{skew}}| > 1.96$ or $|Z_{\\text{kurt}}| > 1.96$ at a $5\\%$ significance level ($\\alpha = 0.05$), the distribution deviates significantly from normality.\n\n## Shapiro-Wilk Test of Normality\n\nThe Shapiro-Wilk Test evaluates the null hypothesis ($H_0$) that a sample comes from a normally distributed population.\n\nNull Hypothesis ($H_0$): The data are normally distributed.\n\nAlternative Hypothesis ($H_1$): The data are not normally distributed.\n\nA $p$-value lower than the chosen threshold ($\\alpha = 0.05$) leads to rejecting $H_0$, indicating significant deviation from a normal distribution.\n\nLet's plot two samples of $n = 100$: one from a standard normal distribution and another from an exponential distribution.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\nTable: Shapiro-Wilk Test Results\n\n|Dataset                      | Statistic_W|p_value   |Interpretation                          |\n|:----------------------------|-----------:|:---------|:---------------------------------------|\n|Simulated Normal Sample      |      0.9939|0.9349    |Fail to reject H0 (Data appears Normal) |\n|Simulated Exponential Sample |      0.8740|1.016e-07 |Reject H0 (Non-Normal)                  |\n\n\n:::\n:::\n\n\n\n# Descriptive Statistics using Graphics\n\nGraphical representations of data provide intuitive visual summaries of distributions, patterns, trends, and relationships. Unlike numerical descriptive measures (such as mean or standard deviation), graphical methods allow researchers to quickly spot outliers, skewness, multimodal behavior, and temporal trends.\n\n## Barplot\n\nA **barplot** (or bar chart) is a graphical display that represents categorical data using rectangular bars, where the length or height of each bar is proportional to the count, frequency, or percentage of observations falling into each category.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Time series plot\n\nA **time series plot** is a line chart where observations recorded sequentially over regular time intervals are plotted against time on the horizontal axis. It is used to analyze patterns such as secular trends, seasonality, cyclical fluctuations, and irregular variations over time.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=720}\n:::\n:::\n\n\n## Stacked bar plot\n\nA **stacked bar plot** extends a standard bar plot by dividing each bar into sub-bars representing sub-categories within the main category. It allows simultaneous comparison of total quantities and internal compositions.\n\n- **Normal (Absolute) Stacked Bar Plot:** Displays the raw counts or values stacked vertically. The height of the entire bar represents the total aggregate frequency across all sub-categories.\n- **100% Stacked Bar Plot:** Normalizes every bar to 100% (or proportion 1.0). Each sub-bar represents the relative percentage contribution of that sub-category within its parent group, making it easy to compare proportion structures regardless of differing total group sizes.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=912}\n:::\n:::\n\n\n## Histogram and density plot\n\nA **histogram** is a graphical display of the probability distribution of a continuous quantitative variable. The range of values is divided into a series of contiguous, non-overlapping intervals called **bins**. The height of each rectangle corresponds to the frequency or density of data points falling into that bin.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nA histogram visualizes the frequency of data within pre-specified numerical ranges (\"bins\"). Because bin widths can heavily influence the visual output, histograms display a discrete representation of raw counts.\n\nA density plot is a smooth, continuous curve representing the probability density function (PDF) of the underlying data. It estimates the probability of a random variable falling within a given range, where the total area under the density curve equals $1$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Q-Q plot\n\nA **Quantile-Quantile (Q-Q) plot** is a diagnostic scatter plot used to assess whether an empirical sample dataset originates from a theoretical reference distribution (most commonly the Normal Distribution). It plots the empirical sample quantiles on the vertical axis against the theoretical quantiles on the horizontal axis. If the dataset follows the assumed distribution, the points will fall closely along the 45-degree reference line ($y = x$).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Box whisker plot and violin plot\n\nA **box-whisker plot** (or boxplot) provides a concise visual summary of a continuous variable's distribution based on its five-number summary: minimum, first quartile ($Q_1$), median ($Q_2$), third quartile ($Q_3$), and maximum.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=720}\n:::\n:::\n\n\n### Explanation of Box-Whisker Components\n\n1. **The Central Box (Interquartile Range - IQR):**\n   - The lower edge of the box represents the **First Quartile ($Q_1$ / 25th percentile)**.\n   - The upper edge represents the **Third Quartile ($Q_3$ / 75th percentile)**.\n   - The span between $Q_1$ and $Q_3$ is the **Interquartile Range ($IQR = Q_3 - Q_1$)**, which contains the central 50% of the data.\n\n2. **The Median Line ($Q_2$):**\n   - The line drawn across the inside of the box marks the **Median (50th percentile)**.\n   - A median centered within the box suggests a symmetric distribution; a median closer to $Q_1$ indicates positive (right) skewness, while a median closer to $Q_3$ indicates negative (left) skewness.\n\n3. **Whiskers:**\n   - Lines extending from the top and bottom of the box are called **whiskers**.\n   - By default (Tukey boxplot convention), whiskers extend to the furthest data points within $1.5 \\times IQR$ from $Q_1$ and $Q_3$:\n     $$\\text{Lower Whisker Limit} = Q_1 - 1.5 \\times IQR$$\n     $$\\text{Upper Whisker Limit} = Q_3 + 1.5 \\times IQR$$\n\n4. **Outliers:**\n   - Data points located beyond the whiskers (less than $Q_1 - 1.5 \\times IQR$ or greater than $Q_3 + 1.5 \\times IQR$) are identified as **outliers** and plotted individually as distinct points (highlighted in red above).\n\nA **violin plot** combines a box plot with a kernel density plot. It mirrors a smooth density curve along a central axis, illustrating where data points are most concentrated.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n### Key Differences\n\n- Bimodal/Multimodal Data: A box plot might mask a bimodal distribution as a single wide box, whereas a violin plot clearly shows multiple peaks (\"bumps\").\n\n- Sample Density: Violin plots illustrate data density and probability distribution, while box plots emphasize summary statistics and interquartile ranges (IQR).\n\n\n# Jamovi\n\nHere is the output: \n\n\n::: {#tbl:Table_Descriptives}\n                            Fuel Type          Mileage\n  ------------------------- ----------- --------------\n  N                         Diesel              344.00\n                            Electric            325.00\n                            Petrol              331.00\n  Missing                   Diesel                0.00\n                            Electric              0.00\n                            Petrol                0.00\n  Mean                      Diesel            98804.60\n                            Electric          99639.63\n                            Petrol            93114.27\n  95% CI mean lower bound   Diesel            92333.13\n                            Electric          93234.14\n                            Petrol            86791.29\n  95% CI mean upper bound   Diesel           105276.07\n                            Electric         106045.11\n                            Petrol            99437.26\n  Median                    Diesel            96552.00\n                            Electric          98035.00\n                            Petrol            86332.00\n  Mode                      Diesel         56.00$^{a}$\n                            Electric      319.00$^{a}$\n                            Petrol        246.00$^{a}$\n  Sum                       Diesel             3.40e+7\n                            Electric           3.24e+7\n                            Petrol             3.08e+7\n  Standard deviation        Diesel            61023.78\n                            Electric          58697.59\n                            Petrol            58478.02\n  Variance                  Diesel             3.72e+9\n                            Electric           3.45e+9\n                            Petrol             3.42e+9\n  IQR                       Diesel           116444.25\n                            Electric         105840.00\n                            Petrol            94604.50\n  Range                     Diesel           199811.00\n                            Electric         199202.00\n                            Petrol           198522.00\n  Minimum                   Diesel               56.00\n                            Electric            319.00\n                            Petrol              246.00\n  Maximum                   Diesel           199867.00\n                            Electric         199521.00\n                            Petrol           198768.00\n  Skewness                  Diesel                0.05\n                            Electric              0.07\n                            Petrol                0.14\n  Std. error skewness       Diesel                0.13\n                            Electric              0.14\n                            Petrol                0.13\n  Kurtosis                  Diesel               -1.31\n                            Electric             -1.26\n                            Petrol               -1.17\n  Std. error kurtosis       Diesel                0.26\n                            Electric              0.27\n                            Petrol                0.27\n  Shapiro-Wilk W            Diesel                0.94\n                            Electric              0.95\n                            Petrol                0.95\n  Shapiro-Wilk p            Diesel             \\< .001\n                            Electric           \\< .001\n                            Petrol             \\< .001\n:::\n\n\n::: tablenotes\n*Note.* The CI of the mean assumes sample means follow a t-distribution\nwith N - 1 degrees of freedom\\\n$^{a}$ More than one mode exists, only the first is reported\\\n:::\n\n## Interpretation\n\n- 95% Confidence Interval (CI) of the Mean\n  - Values\n    - Diesel: [92,333.13, 105,276.07]\n    - Electric: [93,234.14, 106,045.11]\n    - Petrol: [86,791.29, 99,437.26]\n\n  Interpretation: There is 95% confidence that the true population mean mileage for each fuel type lies within these bounds. Because the confidence intervals for all three groups overlap heavily, there is no strong initial evidence of a statistically significant difference in mean mileage across the fuel types.\n\n- Interquartile Range (IQR)\n  - Values \n    - Diesel: 116,444.25\n    - Electric: 105,840.00 \n    - Petrol: 94,604.50\n  \n  Interpretation: The IQR represents the spread of the middle 50% of the data ($Q_3 - Q_1$). Diesel vehicles have the widest middle spread (116,444.25 units), while Petrol vehicles have the narrowest (94,604.50 units). Because the mileage distributions deviate from normality, the IQR serves as a robust measure of variability alongside standard deviation.\n\n- Skewness & Std. Error of Skewness ($Z = \\text{Skewness} / \\text{Std. error of Skewness}$)\n  - Values\n    - Diesel: Skewness = 0.05 (SE = 0.13), $Z_{\\text{skew}} = 0.385$\n    - Electric: Skewness = 0.07 (SE = 0.14), $Z_{\\text{skew}} = 0.500$\n    - Petrol: Skewness = 0.14 (SE = 0.13), $Z_{\\text{skew}} = 1.077$\n\n  Interpretation: Skewness measures distribution symmetry (0 = perfectly symmetric). All three groups show slight positive (right) skewness ($0.05$ to $0.14$).Std. Error of Skewness estimates the sampling variability.Dividing skewness by its standard error gives $Z$-scores well within the standard threshold of $\\pm 1.96$, indicating that the slight asymmetry in all three groups is not statistically significant.\n\n- Kurtosis & Std. Error of Kurtosis\n  - Values\n    - Diesel: Kurtosis = -1.31 (SE = 0.26), $Z_{\\text{kurt}} = -5.038$\n    - Electric: Kurtosis = -1.26 (SE = 0.27), $Z_{\\text{kurt}} = -4.667$\n    - Petrol: Kurtosis = -1.17 (SE = 0.27), $Z_{\\text{kurt}} = -4.333$\n  \n  Interpretation: Kurtosis measures the \"peakedness\" and tail weight relative to a normal distribution (0 = mesokurtic/normal). Negative values indicate a platykurtic distribution—flatter top with lighter tails, meaning values are spread relatively evenly across the range (from ~0 to 200,000).Std. Error of Kurtosis quantifies expected sampling variation.The resulting $Z$-scores ($Z = \\text{Kurtosis} / \\text{SE}$) are significantly lower than $-1.96$ across all groups (ranging from $-4.33$ to $-5.04$). This confirms a statistically significant departure from a normal bell curve due to extreme flatness.\n\nShapiro-Wilk $W$ and $p$-value\n  - Values\n    - Diesel: $W = 0.94$, $p < .001$\n    - Electric: $W = 0.95$, $p < .001$\n    - Petrol: $W = 0.95$, $p < .001$\n  \nInterpretation\n    - Shapiro-Wilk $W$ evaluates how closely the sample distribution matches a normal distribution ($W = 1.00$ indicates a perfect normal fit).\n    \n    - Shapiro-Wilk $p$-value tests the null hypothesis that the data is normally distributed.\n    \n    - Because $p < .001$ for all three groups, the null hypothesis of normality is rejected at standard significance levels ($\\alpha = .05$). The mileage data is significantly non-normal (driven primarily by the flat, platykurtic shape).\n\n### Key Takeaway for Further Analysis\n\nBecause the assumption of normality is violated (p<.001), parametric tests such as standard one-way ANOVA may be invalid unless sample sizes (N>300 per group) provide sufficient robustness via the Central Limit Theorem. Non-parametric alternatives like the Kruskal-Wallis test or robust ANOVA methods are recommended for comparing mileage across fuel types.",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}