<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Haseeb Mahmud">
<meta name="dcterms.date" content="2026-09-28">

<title>Descriptive Statistics – Applied Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-55617497126496852ff9f5a59253c640.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Applied Data Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/adsheilbronn"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://ilias.hs-heilbronn.de/ilias.php?baseClass=ilrepositorygui&amp;ref_id=1078855"> <i class="bi bi-mortarboard" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Descriptive Statistics</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Haseeb Mahmud </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 28, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#measures-of-central-tendency" id="toc-measures-of-central-tendency" class="nav-link active" data-scroll-target="#measures-of-central-tendency">Measures of central Tendency</a>
  <ul class="collapse">
  <li><a href="#arithmetic-mean" id="toc-arithmetic-mean" class="nav-link" data-scroll-target="#arithmetic-mean">Arithmetic mean</a>
  <ul class="collapse">
  <li><a href="#some-comments-about-the-arithmetic-mean" id="toc-some-comments-about-the-arithmetic-mean" class="nav-link" data-scroll-target="#some-comments-about-the-arithmetic-mean">Some comments about the arithmetic mean</a></li>
  </ul></li>
  <li><a href="#median" id="toc-median" class="nav-link" data-scroll-target="#median">Median</a>
  <ul class="collapse">
  <li><a href="#median-some-comments" id="toc-median-some-comments" class="nav-link" data-scroll-target="#median-some-comments">Median: some comments</a></li>
  </ul></li>
  <li><a href="#mode" id="toc-mode" class="nav-link" data-scroll-target="#mode">Mode</a>
  <ul class="collapse">
  <li><a href="#mode-some-comments" id="toc-mode-some-comments" class="nav-link" data-scroll-target="#mode-some-comments">Mode: some comments</a></li>
  </ul></li>
  <li><a href="#relationship-mean-median-mode" id="toc-relationship-mean-median-mode" class="nav-link" data-scroll-target="#relationship-mean-median-mode">Relationship: mean, Median, Mode</a></li>
  </ul></li>
  <li><a href="#measures-of-dispersion" id="toc-measures-of-dispersion" class="nav-link" data-scroll-target="#measures-of-dispersion">Measures of dispersion</a>
  <ul class="collapse">
  <li><a href="#range" id="toc-range" class="nav-link" data-scroll-target="#range">Range</a></li>
  <li><a href="#variance-and-standard-deviation" id="toc-variance-and-standard-deviation" class="nav-link" data-scroll-target="#variance-and-standard-deviation">Variance and standard deviation</a>
  <ul class="collapse">
  <li><a href="#variance-and-standard-deviation-example" id="toc-variance-and-standard-deviation-example" class="nav-link" data-scroll-target="#variance-and-standard-deviation-example">Variance and standard deviation: Example</a></li>
  <li><a href="#characteristics-of-deviation-measures" id="toc-characteristics-of-deviation-measures" class="nav-link" data-scroll-target="#characteristics-of-deviation-measures">Characteristics of deviation measures</a></li>
  </ul></li>
  <li><a href="#the-coefficient-of-variation" id="toc-the-coefficient-of-variation" class="nav-link" data-scroll-target="#the-coefficient-of-variation">The coefficient of variation</a></li>
  </ul></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a>
  <ul class="collapse">
  <li><a href="#confidence-interval-large-sample" id="toc-confidence-interval-large-sample" class="nav-link" data-scroll-target="#confidence-interval-large-sample">Confidence interval: large sample</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central limit theorem</a></li>
  </ul></li>
  <li><a href="#covariance-and-correlation" id="toc-covariance-and-correlation" class="nav-link" data-scroll-target="#covariance-and-correlation">Covariance and correlation</a>
  <ul class="collapse">
  <li><a href="#percentiles" id="toc-percentiles" class="nav-link" data-scroll-target="#percentiles">Percentiles</a></li>
  <li><a href="#skewness-and-kurtosis" id="toc-skewness-and-kurtosis" class="nav-link" data-scroll-target="#skewness-and-kurtosis">3. Skewness and Kurtosis</a>
  <ul class="collapse">
  <li><a href="#visualizing-skewness-kurtosis-impact" id="toc-visualizing-skewness-kurtosis-impact" class="nav-link" data-scroll-target="#visualizing-skewness-kurtosis-impact">Visualizing Skewness &amp; Kurtosis Impact</a></li>
  <li><a href="#assessing-normality-via-skewness-and-kurtosis" id="toc-assessing-normality-via-skewness-and-kurtosis" class="nav-link" data-scroll-target="#assessing-normality-via-skewness-and-kurtosis">Assessing Normality via Skewness and Kurtosis</a></li>
  </ul></li>
  <li><a href="#shapiro-wilk-test-of-normality" id="toc-shapiro-wilk-test-of-normality" class="nav-link" data-scroll-target="#shapiro-wilk-test-of-normality">Shapiro-Wilk Test of Normality</a></li>
  </ul></li>
  <li><a href="#descriptive-statistics-using-graphics" id="toc-descriptive-statistics-using-graphics" class="nav-link" data-scroll-target="#descriptive-statistics-using-graphics">Descriptive Statistics using Graphics</a>
  <ul class="collapse">
  <li><a href="#barplot" id="toc-barplot" class="nav-link" data-scroll-target="#barplot">Barplot</a></li>
  <li><a href="#time-series-plot" id="toc-time-series-plot" class="nav-link" data-scroll-target="#time-series-plot">Time series plot</a></li>
  <li><a href="#stacked-bar-plot" id="toc-stacked-bar-plot" class="nav-link" data-scroll-target="#stacked-bar-plot">Stacked bar plot</a></li>
  <li><a href="#histogram-and-density-plot" id="toc-histogram-and-density-plot" class="nav-link" data-scroll-target="#histogram-and-density-plot">Histogram and density plot</a></li>
  <li><a href="#q-q-plot" id="toc-q-q-plot" class="nav-link" data-scroll-target="#q-q-plot">Q-Q plot</a></li>
  <li><a href="#box-whisker-plot-and-violin-plot" id="toc-box-whisker-plot-and-violin-plot" class="nav-link" data-scroll-target="#box-whisker-plot-and-violin-plot">Box whisker plot and violin plot</a>
  <ul class="collapse">
  <li><a href="#explanation-of-box-whisker-components" id="toc-explanation-of-box-whisker-components" class="nav-link" data-scroll-target="#explanation-of-box-whisker-components">Explanation of Box-Whisker Components</a></li>
  <li><a href="#key-differences" id="toc-key-differences" class="nav-link" data-scroll-target="#key-differences">Key Differences</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#jamovi" id="toc-jamovi" class="nav-link" data-scroll-target="#jamovi">Jamovi</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a>
  <ul class="collapse">
  <li><a href="#key-takeaway-for-further-analysis" id="toc-key-takeaway-for-further-analysis" class="nav-link" data-scroll-target="#key-takeaway-for-further-analysis">Key Takeaway for Further Analysis</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="measures-of-central-tendency" class="level1">
<h1>Measures of central Tendency</h1>
<section id="arithmetic-mean" class="level2">
<h2 class="anchored" data-anchor-id="arithmetic-mean">Arithmetic mean</h2>
<p>The arithmetic mean, or mean of a set of measurements is defined to be the sum of measurements divided by the total number of measurements.</p>
<p>Usually, the population mean is denoted by <span class="math inline">\(\mu\)</span> and the sample mean is denoted by <span class="math inline">\(\bar{y}\)</span>. The sample mean of a series is defined as,</p>
<p><span class="math display">\[
\bar{y}=\frac{\sum_iY_i}{n}
\]</span></p>
<p>where, <span class="math inline">\(n\)</span> is the number of observations.</p>
<p>Example A sample of <span class="math inline">\(n=15\)</span> overdue accounts in a large department store yields the following amounts due,</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td>55.2</td>
<td>4.88</td>
<td>271.95</td>
</tr>
<tr class="even">
<td>18.06</td>
<td>180.29</td>
<td>365.29</td>
</tr>
<tr class="odd">
<td>28.16</td>
<td>399.11</td>
<td>807.8</td>
</tr>
<tr class="even">
<td>44.14</td>
<td>97.47</td>
<td>9.98</td>
</tr>
<tr class="odd">
<td>61.61</td>
<td>56.89</td>
<td>82.73</td>
</tr>
</tbody>
</table>
<p>The sample mean is computed as follows,</p>
<p><span class="math display">\[
\bar{y}= \frac{\sum_iY_i}{n}=\frac{55.20+18.06+ .... + 82.73}{15}=\frac{2483.56}{15}=165.57
\]</span></p>
<section id="some-comments-about-the-arithmetic-mean" class="level3">
<h3 class="anchored" data-anchor-id="some-comments-about-the-arithmetic-mean">Some comments about the arithmetic mean</h3>
<ul>
<li>It is the most common central tendency measure</li>
<li>There exist only one mean of a dataset/series</li>
<li>The value of the mean is influenced by the extreme values. Trimming or deleting extreme observations helps to reduce/omit that influence</li>
<li>Means of samples from a single population can be combined to get the population mean.</li>
<li>It is applicable to quantitative data only.</li>
</ul>
</section>
</section>
<section id="median" class="level2">
<h2 class="anchored" data-anchor-id="median">Median</h2>
<p>The median of a set of measurements is defined to be the middle value when the measurements are arranged from lowest to highest. So, first we need to sort the dataset from lowest to highest.</p>
<p><span class="math display">\[
y_1 \leq y_2 \leq y_3 \leq .... \leq y_i \leq .. \leq y_n
\]</span></p>
<p>Then, the median of a series will be,</p>
<ul>
<li><span class="math inline">\(\frac{N+1}{2}\)</span>-th observation if <span class="math inline">\(n\)</span> is odd.</li>
<li>Average of <span class="math inline">\(\left(\frac{N}{2}\right)\)</span> and <span class="math inline">\(\left(\frac{N}{2}+1\right)\)</span>-th observation if <span class="math inline">\(n\)</span> is even.</li>
</ul>
<section id="median-some-comments" class="level3">
<h3 class="anchored" data-anchor-id="median-some-comments">Median: some comments</h3>
<ul>
<li>It is the central value, 50 percent of the observations lie above it and the rest fall below it.</li>
<li>There is only one median in a dataset</li>
<li>It is not affected by extreme observations</li>
<li>Medians of subsamples cannot be combined to get the median of the population.</li>
<li>It is applicable to quantitative data only</li>
<li>For group data, its value is rather stable even when the data are organized into different categories.</li>
</ul>
</section>
</section>
<section id="mode" class="level2">
<h2 class="anchored" data-anchor-id="mode">Mode</h2>
<p>A mode of a set of measurements is defined to be the measurement that occurs most often, i.e.&nbsp;the highest frequency.</p>
<section id="mode-some-comments" class="level3">
<h3 class="anchored" data-anchor-id="mode-some-comments">Mode: some comments</h3>
<p>There can be more than one mode in a dataseries. Modes of the subsamples cann’t be used to determine to formulate the mode of the population It is applicable for both qualitative and quantitative data For grouped data, its value can change depending on the categories used.</p>
</section>
</section>
<section id="relationship-mean-median-mode" class="level2">
<h2 class="anchored" data-anchor-id="relationship-mean-median-mode">Relationship: mean, Median, Mode</h2>
<ul>
<li>When a variable is normally distributed, the mean, median, and mode are the same number.</li>
<li>When the variable is skewed to the left (i.e., negatively skewed), the mean shifts to the left the most, the median shifts to the left the second most, and the mode the least affected by the presence of skew in the data.</li>
<li>When the variable is skewed to the right (i.e., positively skewed), the mean is shifted to the right the most, the median is shifted to the right the second most, and the mode the least affected.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="2_1.png" class="img-fluid figure-img"></p>
<figcaption>Relationship among different central tendency measures</figcaption>
</figure>
</div>
</section>
</section>
<section id="measures-of-dispersion" class="level1">
<h1>Measures of dispersion</h1>
<section id="range" class="level2">
<h2 class="anchored" data-anchor-id="range">Range</h2>
<p>The range of a set of measurements is defined to be the difference between the largest and the smallest measurements of the set.</p>
<p>From the above dataset we are working on, the smallest values is 4.88 and the largest is 807.80. The range of the data would be,</p>
<p><span class="math display">\[
range = 807.80 - 4.88 = 802.92
\]</span></p>
</section>
<section id="variance-and-standard-deviation" class="level2">
<h2 class="anchored" data-anchor-id="variance-and-standard-deviation">Variance and standard deviation</h2>
<p>The <em>variance</em> of a set of measurements <span class="math inline">\(y_1, y_2, y_3, .... , y_n\)</span>, with a mean of <span class="math inline">\(\bar{y}_n\)</span> is the sum of the squared deviations divided by <span class="math inline">\(n-1\)</span>. Symbolically,</p>
<p><span class="math display">\[
s^2 = \frac{\sum_{i=1}^n(x_i-\bar{x})^2}{n-1}
\]</span></p>
<p>We are assuming, we are working with <strong>samples</strong>. In case of variance we will replace <span class="math inline">\(n-1\)</span> with <span class="math inline">\(n\)</span> in the denominator. Sample variance is denoted by <span class="math inline">\(s^2\)</span> and the population variance is denoted by <span class="math inline">\(\sigma^2\)</span>.</p>
<p>Sample variance is an <em>unbiased estimator</em> of the population variance. That means, if we take different sub-samples from the population, then the average variance of those samples are (roughly) equal to the population variance.</p>
<p>The <strong>standard deviation</strong> is a set of measurements is defined to be the positive square root of the variance. <span class="math display">\[
s = \sqrt{\frac{\sum_{i=1}^n(x_i-\bar{x})^2}{n-1}}
\]</span></p>
<p>As mentioned before, sample standard deviation will be denoted by <span class="math inline">\(s\)</span> and the population standard deviation is denoted by <span class="math inline">\(\sigma\)</span>. In real life, this difference is often ignored.</p>
<section id="variance-and-standard-deviation-example" class="level3">
<h3 class="anchored" data-anchor-id="variance-and-standard-deviation-example">Variance and standard deviation: Example</h3>
<table class="caption-top table">
<caption>Calories in different Starbucks drinks</caption>
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Product</th>
<th>Calories</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dunkin’s Donuts Iced Mocha Swirl latte (whole milk)</td>
<td>240</td>
</tr>
<tr class="even">
<td>Starbucks coffee frappuccino blended coffee</td>
<td>260</td>
</tr>
<tr class="odd">
<td>Dunkin Donuts coffee coolatta</td>
<td>350</td>
</tr>
<tr class="even">
<td>Starbucks Iced Coffee Mocha Espresso (whole Milk and whipped cream</td>
<td>350</td>
</tr>
<tr class="odd">
<td>Starbucks Mocha Flappuccino blended coffee (whipped cream)</td>
<td>420</td>
</tr>
<tr class="even">
<td>Starbucks Chocolate Brownie Flappuccino blended coffee (whipped cream)</td>
<td>510</td>
</tr>
<tr class="odd">
<td>Starbucks Chocolate Flappuccino blended creme (whipped cream</td>
<td>530</td>
</tr>
</tbody>
</table>
<p>To calculate standard deviation and variance first we need to calculate the mean, then the squared differences</p>
<p><span class="math display">\[
\bar{x} = \frac{\sum_{i=1}^nX_i}{n} = \frac{2660}{7} = 380
\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Calories</th>
<th><span class="math inline">\((x_i - \bar{x})\)</span></th>
<th><span class="math inline">\((x_i - \bar{x})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>240</td>
<td>-140</td>
<td>19600</td>
</tr>
<tr class="even">
<td>260</td>
<td>-120</td>
<td>14400</td>
</tr>
<tr class="odd">
<td>350</td>
<td>-30</td>
<td>900</td>
</tr>
<tr class="even">
<td>350</td>
<td>-30</td>
<td>900</td>
</tr>
<tr class="odd">
<td>420</td>
<td>40</td>
<td>1600</td>
</tr>
<tr class="even">
<td>510</td>
<td>130</td>
<td>16900</td>
</tr>
<tr class="odd">
<td>530</td>
<td>150</td>
<td>22500</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>76800</td>
</tr>
</tbody>
</table>
<p>Putting all into the formula, we can get the variance.</p>
<p><span class="math display">\[
s^2 = \frac{\sum_{i=1}^n(x_i-\bar{x})^2}{n-1} = \frac{76800}{6} =  12800
\]</span><br>
And, the standard deviation is,</p>
<p><span class="math display">\[
s = \sqrt{s^2} = \sqrt{12800} = 113.1371
\]</span></p>
</section>
<section id="characteristics-of-deviation-measures" class="level3">
<h3 class="anchored" data-anchor-id="characteristics-of-deviation-measures">Characteristics of deviation measures</h3>
<ul>
<li>The greater the spread or dispersion of the data, the larger the range, <span class="math inline">\(\sigma^2\)</span> and <span class="math inline">\(\sigma\)</span>.</li>
<li>The greater the concentration of the data around the central value, the smaller the range, <span class="math inline">\(\sigma^2\)</span> and <span class="math inline">\(\sigma\)</span>.</li>
<li>If the values are all the same (so that there are no variation in the data), the range, <span class="math inline">\(\sigma^2\)</span> and <span class="math inline">\(\sigma\)</span> will all equal to zero.</li>
<li>None of the measures of variation can <em>ever</em> be negative.</li>
</ul>
</section>
</section>
<section id="the-coefficient-of-variation" class="level2">
<h2 class="anchored" data-anchor-id="the-coefficient-of-variation">The coefficient of variation</h2>
<p>Unlike the range, <span class="math inline">\(\sigma\)</span> and <span class="math inline">\(\sigma^2\)</span>, the coefficient of variation is a relative measure expressed as a percentage rather than units of a particular data. The coefficient of variation is equal to the standard deviation by the mean, multiplied by <span class="math inline">\(100\%\)</span>.</p>
<p><span class="math display">\[
CV = \left(\frac{\sigma}{\bar{x}}\right)\times 100\%
\]</span></p>
<p>The coefficient of variation is particularly useful to compare the variability of two different datasets measured in two different units of measurements.</p>
<p>From the previous Starbucks data, the coefficient of variation can be calculated as,</p>
<p><span class="math display">\[
CV = \left(\frac{s}{\bar{x}}\right)\times 100\% = \frac{113.1371}{380} \times 100\% = 28.79\%
\]</span></p>
</section>
</section>
<section id="confidence-intervals" class="level1">
<h1>Confidence Intervals</h1>
<p>The goal here is to estimate the sample information to estimate the population parameter of interest to assess the reliability of the estimate.</p>
<ul>
<li>The unknown population parameter (e.g.&nbsp;mean or proportion) that we are interested in estimating is called <em>target parameter</em>}.</li>
<li>A <em>point estimator</em> of a population is a rule or formula that tells us how to use the sample data to calculate as single number that can be used as an estimate of the target parameter.</li>
<li>An <em>interval estimator or confidence interval</em> is a formula that tells us how to use the sample data to calculate an interval that estimates the target parameter.</li>
</ul>
<section id="confidence-interval-large-sample" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-large-sample">Confidence interval: large sample</h2>
<p><strong>CI for a</strong> <span class="math inline">\(\mu\)</span>: Normal <span class="math inline">\(z\)</span>-statistic</p>
<p>Let <span class="math inline">\(x_1, x_2, ... , x_n\)</span> be a random sample of <span class="math inline">\(n\)</span> observations from a normally distributed population with unknown mean <span class="math inline">\(\mu\)</span> and known <span class="math inline">\(\sigma^2\)</span>. Suppose that, we want a <span class="math inline">\(100(1-\alpha)\%\)</span> CI of the population mean. Previously, we saw that,</p>
<p><span class="math display">\[
z = \frac{\bar{x}-\mu}{\sigma/\sqrt{n}}
\]</span></p>
<p>has a <span class="math inline">\(N(0,1)\)</span> distribution and <span class="math inline">\(z_{\alpha/2}\)</span> is the value from the <span class="math inline">\(N(0,1)\)</span> such that the upper tail probability is <span class="math inline">\(\alpha/2\)</span>. We use the basis algebra to find,</p>
<p><span class="math display">\[
1 - \alpha =  \mathbb{P} (-z_{\alpha/2} &lt; z &lt; z_{\alpha/2}) = \mathbb{P} \left(-z_{\alpha/2} &lt; \frac{\bar{x}-\mu}{\sigma/\sqrt{n}} &lt; z_{\alpha/2}\right)
\]</span></p>
<p>which in turn,</p>
<p><span class="math display">\[
\mathbb{P} \left(-z_{\alpha/2} \frac{\sigma}{\sqrt{n}} &lt; \bar{x} - \mu &lt; z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)
= \mathbb{P} \left(\bar{x}-z_{\alpha/2} \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \bar{x}+z_{\alpha/2}\frac{\sigma}{\sqrt{n}}\right)
\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="central-limit-theorem" class="level2">
<h2 class="anchored" data-anchor-id="central-limit-theorem">Central limit theorem</h2>
<p>According to the Central Limit Theorem the sampling distribution of the sample mean is approximately normal for large samples. For a <span class="math inline">\(95\%\)</span> confidence level it follows that,</p>
<p><span class="math display">\[
\mathbb{P} \left(\bar{x}-1.96 \frac{\sigma}{\sqrt{n}} &lt; \mu &lt; \bar{x}+1.96\frac{\sigma}{\sqrt{n}}\right)
\]</span></p>
<p>The interval <span class="math inline">\(\bar{x} \pm 1.96\sigma_{\bar{x}}\)</span> is called the large sample <span class="math inline">\(95\%\)</span> confidence interval for the population mean <span class="math inline">\(\mu\)</span>. The term large sample refers to the sample being of sufficiently large size that we can apply the Central Limit Theory and the normal <span class="math inline">\(z\)</span> statistic to determine the form of the sampling distribution of <span class="math inline">\(\bar{x}\)</span>. Empirical research suggests that a sample size <span class="math inline">\(n\)</span> exceeding a value between 20 and 30 will usually yield a sampling distribution of <span class="math inline">\(\bar{x}\)</span>, that is normal.</p>
<p>If the sample means (e.g.&nbsp;<span class="math inline">\(\bar{x}_1, \bar{x}_3\)</span> and <span class="math inline">\(\bar{x}_4\)</span>) falls between the two lines on either side of <span class="math inline">\(\mu\)</span>, then the interval <span class="math inline">\(\bar{x} \pm 1.96\sigma_{\bar{x}}\)</span> will contain <span class="math inline">\(\mu\)</span>; if <span class="math inline">\(\bar{x}\)</span> falls outside the boundaries (e.g.&nbsp;<span class="math inline">\(\bar{x}_2\)</span>), the interval <span class="math inline">\(\bar{x} \pm 1.96\sigma_{\bar{x}}\)</span> will not contain <span class="math inline">\(\mu\)</span>.\ From the Empirical rule, we know that, the area under the normal curve (the sampling distribution of <span class="math inline">\(\bar{x}\)</span> between these boundaries is exactly 0.95. Thus the probability that a randomly selected interval <span class="math inline">\(\bar{x} \pm 1.96\sigma_{\bar{x}}\)</span>, will contain <span class="math inline">\(\mu\)</span> is equal to <span class="math inline">\(0.95\)</span> or <span class="math inline">\(95\%\)</span>.\ Large sample interval estimator requires knowing the value of the population <span class="math inline">\(\sigma\)</span>. In most practical applications, the value of population <span class="math inline">\(\sigma\)</span> is unknown. For large samples, in the absence of <span class="math inline">\(\sigma\)</span>, sample standard deviation <span class="math inline">\(s\)</span> provides a good approximation to <span class="math inline">\(\sigma\)</span>.</p>
</section>
</section>
<section id="covariance-and-correlation" class="level1">
<h1>Covariance and correlation</h1>
<p>Covariance is a measure of the relationship between two random variables. The metric evaluates how much - to what extent - the variables change together. In other words, it is essentially a measure of the variance between two variables. However, the metric does not assess the dependency between variables.</p>
<p><span class="math display">\[
Cov (x, y) = \frac{\sum(x_i - \bar{x})(y_i - \bar{y})}{n}
\]</span></p>
<p>For a sample covariance, we need to deduct 1 from the demoninator, i.e.&nbsp;<span class="math inline">\((n-1)\)</span>.</p>
<ul>
<li>Positive covariance: Indicates that two variables tend to move in the same direction.</li>
<li>Negative covariance: Reveals that two variables tend to move in inverse directions.</li>
</ul>
<p>Using covariance, we can only gauge the direction of the relationship (whether the variables tend to move in tandem or show an inverse relationship). However, it does not indicate the strength of the relationship, nor the dependency between the variables.</p>
<p>Correlation measures the strength of the relationship between variables. Correlation is the scaled measure of covariance. It is dimensionless. In other words, the correlation coefficient is always a pure value and not measured in any units.</p>
<p><span class="math display">\[
\rho = \frac{cov(x, y)}{\sigma_x \sigma_y}
\]</span></p>
<ul>
<li>Correlation value ranges from <span class="math inline">\(-1\)</span> to <span class="math inline">\(+1\)</span>. The correlation of zero indicates zero relationship.</li>
<li><span class="math inline">\(\rho_{x,y} = \rho_{y,x}\)</span></li>
<li>The correlation is not synonimous to causation!</li>
<li>More on this topic will be covered later in the degree program.</li>
</ul>
<section id="percentiles" class="level2">
<h2 class="anchored" data-anchor-id="percentiles">Percentiles</h2>
<p>The <span class="math inline">\(p\)</span>-th percentile of a set of <span class="math inline">\(n\)</span>-measurements arranged in order of magnitude is that value that has at most <span class="math inline">\(p\%\)</span> of the measurements below it and at most <span class="math inline">\((100-p)\%\)</span> above it.</p>
<p>Percentiles are frequently used to describe the results of achievements test scores and the ranking of a person in comparison to the rest of the people taking the examination. Specific percentile of interest are the 25th, 50th and 75th percentiles; often called the lower quantile, the middle quantile (median) and the upper quantile respectively. Similarly, if we divide the data by 10 parts then we refer every part as <em>deciles</em>.</p>
</section>
<section id="skewness-and-kurtosis" class="level2">
<h2 class="anchored" data-anchor-id="skewness-and-kurtosis">3. Skewness and Kurtosis</h2>
<p><strong>Skewness</strong> measures the asymmetry of a probability distribution around its mean:</p>
<ul>
<li><p><strong>Zero Skewness:</strong> Symmetric distribution, where mean, median, and mode coincide (e.g., standard normal distribution).</p></li>
<li><p><strong>Positive (Right) Skewness:</strong> Long tail extending to the right (<span class="math inline">\(\text{mode} \le \text{median} \le \text{mean}\)</span>).</p></li>
<li><p><strong>Negative (Left) Skewness:</strong> Long tail extending to the left (<span class="math inline">\(\text{mean} \le \text{median} \le \text{mode}\)</span>).</p></li>
</ul>
<p><strong>Kurtosis</strong> measures the tail heaviness and peakedness relative to a normal distribution:</p>
<ul>
<li><p><strong>Mesokurtic (Normal):</strong> Excess kurtosis <span class="math inline">\(\approx 0\)</span> (Standard Kurtosis <span class="math inline">\(= 3\)</span>).</p></li>
<li><p><strong>Leptokurtic (Heavy-tailed / High Peak):</strong> Excess kurtosis <span class="math inline">\(&gt; 0\)</span>; higher probability of extreme values or outliers.</p></li>
<li><p><strong>Platykurtic (Light-tailed / Flat Peak):</strong> Excess kurtosis <span class="math inline">\(&lt; 0\)</span>; fewer extreme outliers.</p></li>
</ul>
<section id="visualizing-skewness-kurtosis-impact" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-skewness-kurtosis-impact">Visualizing Skewness &amp; Kurtosis Impact</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="assessing-normality-via-skewness-and-kurtosis" class="level3">
<h3 class="anchored" data-anchor-id="assessing-normality-via-skewness-and-kurtosis">Assessing Normality via Skewness and Kurtosis</h3>
<p>To determine whether data is normally distributed based on sample skewness and excess kurtosis:</p>
<ol type="1">
<li><p><strong>Rules of Thumb for Acceptable Normality</strong></p>
<ul>
<li><strong>Skewness:</strong> Values between <span class="math inline">\(-0.5\)</span> and <span class="math inline">\(+0.5\)</span> indicate near symmetry; values between <span class="math inline">\(-1.0\)</span> and <span class="math inline">\(+1.0\)</span> are generally acceptable for parametric statistics.</li>
<li><strong>Excess Kurtosis:</strong> Values between <span class="math inline">\(-1.0\)</span> and <span class="math inline">\(+1.0\)</span> indicate a near-normal tail structure.</li>
</ul></li>
<li><p><strong>Standardized Z-Score Method</strong></p>
<p>Calculate <span class="math inline">\(Z\)</span>-scores for skewness (<span class="math inline">\(Z_{\text{skew}}\)</span>) and kurtosis (<span class="math inline">\(Z_{\text{kurt}}\)</span>): <span class="math display">\[Z_{\text{skew}} = \frac{\text{Skewness}}{\text{SE}_{\text{skew}}}\]</span> Where <span class="math inline">\(\text{SE}_{\text{skew}} \approx \sqrt{\frac{6}{N}}\)</span>. If <span class="math inline">\(|Z_{\text{skew}}| &gt; 1.96\)</span> or <span class="math inline">\(|Z_{\text{kurt}}| &gt; 1.96\)</span> at a <span class="math inline">\(5\%\)</span> significance level (<span class="math inline">\(\alpha = 0.05\)</span>), the distribution deviates significantly from normality.</p></li>
</ol>
</section>
</section>
<section id="shapiro-wilk-test-of-normality" class="level2">
<h2 class="anchored" data-anchor-id="shapiro-wilk-test-of-normality">Shapiro-Wilk Test of Normality</h2>
<p>The Shapiro-Wilk Test evaluates the null hypothesis (<span class="math inline">\(H_0\)</span>) that a sample comes from a normally distributed population.</p>
<p>Null Hypothesis (<span class="math inline">\(H_0\)</span>): The data are normally distributed.</p>
<p>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>): The data are not normally distributed.</p>
<p>A <span class="math inline">\(p\)</span>-value lower than the chosen threshold (<span class="math inline">\(\alpha = 0.05\)</span>) leads to rejecting <span class="math inline">\(H_0\)</span>, indicating significant deviation from a normal distribution.</p>
<p>Let’s plot two samples of <span class="math inline">\(n = 100\)</span>: one from a standard normal distribution and another from an exponential distribution.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Shapiro-Wilk Test Results</caption>
<colgroup>
<col style="width: 31%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dataset</th>
<th style="text-align: right;">Statistic_W</th>
<th style="text-align: left;">p_value</th>
<th style="text-align: left;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Simulated Normal Sample</td>
<td style="text-align: right;">0.9939</td>
<td style="text-align: left;">0.9349</td>
<td style="text-align: left;">Fail to reject H0 (Data appears Normal)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Simulated Exponential Sample</td>
<td style="text-align: right;">0.8740</td>
<td style="text-align: left;">1.016e-07</td>
<td style="text-align: left;">Reject H0 (Non-Normal)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="descriptive-statistics-using-graphics" class="level1">
<h1>Descriptive Statistics using Graphics</h1>
<p>Graphical representations of data provide intuitive visual summaries of distributions, patterns, trends, and relationships. Unlike numerical descriptive measures (such as mean or standard deviation), graphical methods allow researchers to quickly spot outliers, skewness, multimodal behavior, and temporal trends.</p>
<section id="barplot" class="level2">
<h2 class="anchored" data-anchor-id="barplot">Barplot</h2>
<p>A <strong>barplot</strong> (or bar chart) is a graphical display that represents categorical data using rectangular bars, where the length or height of each bar is proportional to the count, frequency, or percentage of observations falling into each category.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="time-series-plot" class="level2">
<h2 class="anchored" data-anchor-id="time-series-plot">Time series plot</h2>
<p>A <strong>time series plot</strong> is a line chart where observations recorded sequentially over regular time intervals are plotted against time on the horizontal axis. It is used to analyze patterns such as secular trends, seasonality, cyclical fluctuations, and irregular variations over time.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="stacked-bar-plot" class="level2">
<h2 class="anchored" data-anchor-id="stacked-bar-plot">Stacked bar plot</h2>
<p>A <strong>stacked bar plot</strong> extends a standard bar plot by dividing each bar into sub-bars representing sub-categories within the main category. It allows simultaneous comparison of total quantities and internal compositions.</p>
<ul>
<li><strong>Normal (Absolute) Stacked Bar Plot:</strong> Displays the raw counts or values stacked vertically. The height of the entire bar represents the total aggregate frequency across all sub-categories.</li>
<li><strong>100% Stacked Bar Plot:</strong> Normalizes every bar to 100% (or proportion 1.0). Each sub-bar represents the relative percentage contribution of that sub-category within its parent group, making it easy to compare proportion structures regardless of differing total group sizes.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="912"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="histogram-and-density-plot" class="level2">
<h2 class="anchored" data-anchor-id="histogram-and-density-plot">Histogram and density plot</h2>
<p>A <strong>histogram</strong> is a graphical display of the probability distribution of a continuous quantitative variable. The range of values is divided into a series of contiguous, non-overlapping intervals called <strong>bins</strong>. The height of each rectangle corresponds to the frequency or density of data points falling into that bin.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A histogram visualizes the frequency of data within pre-specified numerical ranges (“bins”). Because bin widths can heavily influence the visual output, histograms display a discrete representation of raw counts.</p>
<p>A density plot is a smooth, continuous curve representing the probability density function (PDF) of the underlying data. It estimates the probability of a random variable falling within a given range, where the total area under the density curve equals <span class="math inline">\(1\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="q-q-plot" class="level2">
<h2 class="anchored" data-anchor-id="q-q-plot">Q-Q plot</h2>
<p>A <strong>Quantile-Quantile (Q-Q) plot</strong> is a diagnostic scatter plot used to assess whether an empirical sample dataset originates from a theoretical reference distribution (most commonly the Normal Distribution). It plots the empirical sample quantiles on the vertical axis against the theoretical quantiles on the horizontal axis. If the dataset follows the assumed distribution, the points will fall closely along the 45-degree reference line (<span class="math inline">\(y = x\)</span>).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="box-whisker-plot-and-violin-plot" class="level2">
<h2 class="anchored" data-anchor-id="box-whisker-plot-and-violin-plot">Box whisker plot and violin plot</h2>
<p>A <strong>box-whisker plot</strong> (or boxplot) provides a concise visual summary of a continuous variable’s distribution based on its five-number summary: minimum, first quartile (<span class="math inline">\(Q_1\)</span>), median (<span class="math inline">\(Q_2\)</span>), third quartile (<span class="math inline">\(Q_3\)</span>), and maximum.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="720"></p>
</figure>
</div>
</div>
</div>
<section id="explanation-of-box-whisker-components" class="level3">
<h3 class="anchored" data-anchor-id="explanation-of-box-whisker-components">Explanation of Box-Whisker Components</h3>
<ol type="1">
<li><strong>The Central Box (Interquartile Range - IQR):</strong>
<ul>
<li>The lower edge of the box represents the <strong>First Quartile (<span class="math inline">\(Q_1\)</span> / 25th percentile)</strong>.</li>
<li>The upper edge represents the <strong>Third Quartile (<span class="math inline">\(Q_3\)</span> / 75th percentile)</strong>.</li>
<li>The span between <span class="math inline">\(Q_1\)</span> and <span class="math inline">\(Q_3\)</span> is the <strong>Interquartile Range (<span class="math inline">\(IQR = Q_3 - Q_1\)</span>)</strong>, which contains the central 50% of the data.</li>
</ul></li>
<li><strong>The Median Line (<span class="math inline">\(Q_2\)</span>):</strong>
<ul>
<li>The line drawn across the inside of the box marks the <strong>Median (50th percentile)</strong>.</li>
<li>A median centered within the box suggests a symmetric distribution; a median closer to <span class="math inline">\(Q_1\)</span> indicates positive (right) skewness, while a median closer to <span class="math inline">\(Q_3\)</span> indicates negative (left) skewness.</li>
</ul></li>
<li><strong>Whiskers:</strong>
<ul>
<li>Lines extending from the top and bottom of the box are called <strong>whiskers</strong>.</li>
<li>By default (Tukey boxplot convention), whiskers extend to the furthest data points within <span class="math inline">\(1.5 \times IQR\)</span> from <span class="math inline">\(Q_1\)</span> and <span class="math inline">\(Q_3\)</span>: <span class="math display">\[\text{Lower Whisker Limit} = Q_1 - 1.5 \times IQR\]</span> <span class="math display">\[\text{Upper Whisker Limit} = Q_3 + 1.5 \times IQR\]</span></li>
</ul></li>
<li><strong>Outliers:</strong>
<ul>
<li>Data points located beyond the whiskers (less than <span class="math inline">\(Q_1 - 1.5 \times IQR\)</span> or greater than <span class="math inline">\(Q_3 + 1.5 \times IQR\)</span>) are identified as <strong>outliers</strong> and plotted individually as distinct points (highlighted in red above).</li>
</ul></li>
</ol>
<p>A <strong>violin plot</strong> combines a box plot with a kernel density plot. It mirrors a smooth density curve along a central axis, illustrating where data points are most concentrated.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="key-differences" class="level3">
<h3 class="anchored" data-anchor-id="key-differences">Key Differences</h3>
<ul>
<li><p>Bimodal/Multimodal Data: A box plot might mask a bimodal distribution as a single wide box, whereas a violin plot clearly shows multiple peaks (“bumps”).</p></li>
<li><p>Sample Density: Violin plots illustrate data density and probability distribution, while box plots emphasize summary statistics and interquartile ranges (IQR).</p></li>
</ul>
</section>
</section>
</section>
<section id="jamovi" class="level1">
<h1>Jamovi</h1>
<p>Here is the output:</p>
<div id="tbl:Table_Descriptives">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">&nbsp;</th>
<th style="text-align: left;">Fuel Type</th>
<th style="text-align: right;">Mileage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">N</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">344.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">325.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">331.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Missing</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">98804.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">99639.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">93114.27</td>
</tr>
<tr class="even">
<td style="text-align: left;">95% CI mean lower bound</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">92333.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">93234.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">86791.29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">95% CI mean upper bound</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">105276.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">106045.11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">99437.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Median</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">96552.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">98035.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">86332.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mode</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">56.00<span class="math inline">\(^{a}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">319.00<span class="math inline">\(^{a}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">246.00<span class="math inline">\(^{a}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Sum</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">3.40e+7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">3.24e+7</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">3.08e+7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard deviation</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">61023.78</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">58697.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">58478.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variance</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">3.72e+9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">3.45e+9</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">3.42e+9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IQR</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">116444.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">105840.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">94604.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Range</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">199811.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">199202.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">198522.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Minimum</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">56.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">319.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">246.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maximum</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">199867.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">199521.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">198768.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Skewness</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">0.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">0.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Std. error skewness</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">0.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">0.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">0.13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kurtosis</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">-1.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">-1.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">-1.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Std. error kurtosis</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">0.27</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">0.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Shapiro-Wilk W</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">0.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">0.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shapiro-Wilk p</td>
<td style="text-align: left;">Diesel</td>
<td style="text-align: right;">&lt;&nbsp;.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Electric</td>
<td style="text-align: right;">&lt;&nbsp;.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">&nbsp;</td>
<td style="text-align: left;">Petrol</td>
<td style="text-align: right;">&lt;&nbsp;.001</td>
</tr>
</tbody>
</table>
</div>
<div class="tablenotes">
<p><em>Note.</em>&nbsp;The CI of the mean assumes sample means follow a t-distribution with N - 1 degrees of freedom<br>
<span class="math inline">\(^{a}\)</span>&nbsp;More than one mode exists, only the first is reported<br>
</p>
</div>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<ul>
<li><p>95% Confidence Interval (CI) of the Mean</p>
<ul>
<li>Values
<ul>
<li>Diesel: [92,333.13, 105,276.07]</li>
<li>Electric: [93,234.14, 106,045.11]</li>
<li>Petrol: [86,791.29, 99,437.26]</li>
</ul></li>
</ul>
<p>Interpretation: There is 95% confidence that the true population mean mileage for each fuel type lies within these bounds. Because the confidence intervals for all three groups overlap heavily, there is no strong initial evidence of a statistically significant difference in mean mileage across the fuel types.</p></li>
<li><p>Interquartile Range (IQR)</p>
<ul>
<li>Values
<ul>
<li>Diesel: 116,444.25</li>
<li>Electric: 105,840.00</li>
<li>Petrol: 94,604.50</li>
</ul></li>
</ul>
<p>Interpretation: The IQR represents the spread of the middle 50% of the data (<span class="math inline">\(Q_3 - Q_1\)</span>). Diesel vehicles have the widest middle spread (116,444.25 units), while Petrol vehicles have the narrowest (94,604.50 units). Because the mileage distributions deviate from normality, the IQR serves as a robust measure of variability alongside standard deviation.</p></li>
<li><p>Skewness &amp; Std. Error of Skewness (<span class="math inline">\(Z = \text{Skewness} / \text{Std. error of Skewness}\)</span>)</p>
<ul>
<li>Values
<ul>
<li>Diesel: Skewness = 0.05 (SE = 0.13), <span class="math inline">\(Z_{\text{skew}} = 0.385\)</span></li>
<li>Electric: Skewness = 0.07 (SE = 0.14), <span class="math inline">\(Z_{\text{skew}} = 0.500\)</span></li>
<li>Petrol: Skewness = 0.14 (SE = 0.13), <span class="math inline">\(Z_{\text{skew}} = 1.077\)</span></li>
</ul></li>
</ul>
<p>Interpretation: Skewness measures distribution symmetry (0 = perfectly symmetric). All three groups show slight positive (right) skewness (<span class="math inline">\(0.05\)</span> to <span class="math inline">\(0.14\)</span>).Std. Error of Skewness estimates the sampling variability.Dividing skewness by its standard error gives <span class="math inline">\(Z\)</span>-scores well within the standard threshold of <span class="math inline">\(\pm 1.96\)</span>, indicating that the slight asymmetry in all three groups is not statistically significant.</p></li>
<li><p>Kurtosis &amp; Std. Error of Kurtosis</p>
<ul>
<li>Values
<ul>
<li>Diesel: Kurtosis = -1.31 (SE = 0.26), <span class="math inline">\(Z_{\text{kurt}} = -5.038\)</span></li>
<li>Electric: Kurtosis = -1.26 (SE = 0.27), <span class="math inline">\(Z_{\text{kurt}} = -4.667\)</span></li>
<li>Petrol: Kurtosis = -1.17 (SE = 0.27), <span class="math inline">\(Z_{\text{kurt}} = -4.333\)</span></li>
</ul></li>
</ul>
<p>Interpretation: Kurtosis measures the “peakedness” and tail weight relative to a normal distribution (0 = mesokurtic/normal). Negative values indicate a platykurtic distribution—flatter top with lighter tails, meaning values are spread relatively evenly across the range (from ~0 to 200,000).Std. Error of Kurtosis quantifies expected sampling variation.The resulting <span class="math inline">\(Z\)</span>-scores (<span class="math inline">\(Z = \text{Kurtosis} / \text{SE}\)</span>) are significantly lower than <span class="math inline">\(-1.96\)</span> across all groups (ranging from <span class="math inline">\(-4.33\)</span> to <span class="math inline">\(-5.04\)</span>). This confirms a statistically significant departure from a normal bell curve due to extreme flatness.</p></li>
</ul>
<p>Shapiro-Wilk <span class="math inline">\(W\)</span> and <span class="math inline">\(p\)</span>-value - Values - Diesel: <span class="math inline">\(W = 0.94\)</span>, <span class="math inline">\(p &lt; .001\)</span> - Electric: <span class="math inline">\(W = 0.95\)</span>, <span class="math inline">\(p &lt; .001\)</span> - Petrol: <span class="math inline">\(W = 0.95\)</span>, <span class="math inline">\(p &lt; .001\)</span></p>
<p>Interpretation - Shapiro-Wilk <span class="math inline">\(W\)</span> evaluates how closely the sample distribution matches a normal distribution (<span class="math inline">\(W = 1.00\)</span> indicates a perfect normal fit).</p>
<pre><code>- Shapiro-Wilk $p$-value tests the null hypothesis that the data is normally distributed.

- Because $p &lt; .001$ for all three groups, the null hypothesis of normality is rejected at standard significance levels ($\alpha = .05$). The mileage data is significantly non-normal (driven primarily by the flat, platykurtic shape).</code></pre>
<section id="key-takeaway-for-further-analysis" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaway-for-further-analysis">Key Takeaway for Further Analysis</h3>
<p>Because the assumption of normality is violated (p&lt;.001), parametric tests such as standard one-way ANOVA may be invalid unless sample sizes (N&gt;300 per group) provide sufficient robustness via the Central Limit Theorem. Non-parametric alternatives like the Kruskal-Wallis test or robust ANOVA methods are recommended for comparing mileage across fuel types.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/adsheilbronn\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>