<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Haseeb Mahmud">
<meta name="dcterms.date" content="2026-09-28">

<title>Linear Regression Analysis: From Bivariate to Multiple Regression – Advanced Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-55617497126496852ff9f5a59253c640.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Advanced Data Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/adsheilbronn"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://ilias.hs-heilbronn.de/ilias.php?baseClass=ilrepositorygui&amp;ref_id=1078855"> <i class="bi bi-mortarboard" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Linear Regression Analysis: From Bivariate to Multiple Regression</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Econometrics</div>
                <div class="quarto-category">R</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Haseeb Mahmud </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 28, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#defining-the-concept-of-regression" id="toc-defining-the-concept-of-regression" class="nav-link active" data-scroll-target="#defining-the-concept-of-regression">1. Defining the Concept of Regression</a>
  <ul class="collapse">
  <li><a href="#from-deterministic-functions-to-statistical-models" id="toc-from-deterministic-functions-to-statistical-models" class="nav-link" data-scroll-target="#from-deterministic-functions-to-statistical-models">1.1 From Deterministic Functions to Statistical Models</a></li>
  <li><a href="#the-bivariate-linear-regression-model" id="toc-the-bivariate-linear-regression-model" class="nav-link" data-scroll-target="#the-bivariate-linear-regression-model">1.2 The Bivariate Linear Regression Model</a></li>
  <li><a href="#the-stochastic-error-term-varepsilon_i" id="toc-the-stochastic-error-term-varepsilon_i" class="nav-link" data-scroll-target="#the-stochastic-error-term-varepsilon_i">1.3 The Stochastic Error Term (<span class="math inline">\(\varepsilon_i\)</span>)</a>
  <ul class="collapse">
  <li><a href="#why-does-the-stochastic-error-exist" id="toc-why-does-the-stochastic-error-exist" class="nav-link" data-scroll-target="#why-does-the-stochastic-error-exist">Why Does the Stochastic Error Exist?</a></li>
  <li><a href="#classical-gauss-markov-assumptions-for-ordinary-least-squares-ols" id="toc-classical-gauss-markov-assumptions-for-ordinary-least-squares-ols" class="nav-link" data-scroll-target="#classical-gauss-markov-assumptions-for-ordinary-least-squares-ols">Classical Gauss-Markov Assumptions for Ordinary Least Squares (OLS)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#demonstrating-bivariate-linear-regression" id="toc-demonstrating-bivariate-linear-regression" class="nav-link" data-scroll-target="#demonstrating-bivariate-linear-regression">2. Demonstrating Bivariate Linear Regression</a>
  <ul class="collapse">
  <li><a href="#sample-regression-function-srf-ols-estimation" id="toc-sample-regression-function-srf-ols-estimation" class="nav-link" data-scroll-target="#sample-regression-function-srf-ols-estimation">2.1 Sample Regression Function (SRF) &amp; OLS Estimation</a></li>
  <li><a href="#fitting-the-bivariate-model-in-r" id="toc-fitting-the-bivariate-model-in-r" class="nav-link" data-scroll-target="#fitting-the-bivariate-model-in-r">2.2 Fitting the Bivariate Model in R</a></li>
  <li><a href="#interpretation-of-coefficients" id="toc-interpretation-of-coefficients" class="nav-link" data-scroll-target="#interpretation-of-coefficients">2.3 Interpretation of Coefficients</a></li>
  <li><a href="#partitioning-variance-r2-and-adjusted-r2" id="toc-partitioning-variance-r2-and-adjusted-r2" class="nav-link" data-scroll-target="#partitioning-variance-r2-and-adjusted-r2">2.4 Partitioning Variance: <span class="math inline">\(R^2\)</span> and Adjusted <span class="math inline">\(R^2\)</span></a>
  <ul class="collapse">
  <li><a href="#the-analysis-of-variance-anova-identity" id="toc-the-analysis-of-variance-anova-identity" class="nav-link" data-scroll-target="#the-analysis-of-variance-anova-identity">The Analysis of Variance (ANOVA) Identity</a></li>
  <li><a href="#coefficient-of-determination-r2" id="toc-coefficient-of-determination-r2" class="nav-link" data-scroll-target="#coefficient-of-determination-r2">Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</a></li>
  <li><a href="#why-adjusted-r2-barr2-is-a-better-measure" id="toc-why-adjusted-r2-barr2-is-a-better-measure" class="nav-link" data-scroll-target="#why-adjusted-r2-barr2-is-a-better-measure">Why Adjusted <span class="math inline">\(R^2\)</span> (<span class="math inline">\(\bar{R}^2\)</span>) is a Better Measure</a></li>
  </ul></li>
  <li><a href="#hypothesis-testing-t-test-and-joint-f-test" id="toc-hypothesis-testing-t-test-and-joint-f-test" class="nav-link" data-scroll-target="#hypothesis-testing-t-test-and-joint-f-test">2.5 Hypothesis Testing: <span class="math inline">\(t\)</span>-Test and Joint <span class="math inline">\(F\)</span>-Test</a>
  <ul class="collapse">
  <li><a href="#hypothesis-testing-for-individual-coefficients-t-test" id="toc-hypothesis-testing-for-individual-coefficients-t-test" class="nav-link" data-scroll-target="#hypothesis-testing-for-individual-coefficients-t-test">Hypothesis Testing for Individual Coefficients (<span class="math inline">\(t\)</span>-Test)</a></li>
  <li><a href="#joint-hypothesis-testing-f-test" id="toc-joint-hypothesis-testing-f-test" class="nav-link" data-scroll-target="#joint-hypothesis-testing-f-test">Joint Hypothesis Testing (<span class="math inline">\(F\)</span>-Test)</a></li>
  </ul></li>
  <li><a href="#graphical-representation-of-bivariate-regression" id="toc-graphical-representation-of-bivariate-regression" class="nav-link" data-scroll-target="#graphical-representation-of-bivariate-regression">2.6 Graphical Representation of Bivariate Regression</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression-mlr-model" id="toc-multiple-linear-regression-mlr-model" class="nav-link" data-scroll-target="#multiple-linear-regression-mlr-model">3. Multiple Linear Regression (MLR) Model</a>
  <ul class="collapse">
  <li><a href="#mathematical-specification" id="toc-mathematical-specification" class="nav-link" data-scroll-target="#mathematical-specification">3.1 Mathematical Specification</a></li>
  <li><a href="#demonstrating-multivariate-regression-in-r" id="toc-demonstrating-multivariate-regression-in-r" class="nav-link" data-scroll-target="#demonstrating-multivariate-regression-in-r">3.2 Demonstrating Multivariate Regression in R</a></li>
  <li><a href="#interpreting-mlr-results" id="toc-interpreting-mlr-results" class="nav-link" data-scroll-target="#interpreting-mlr-results">3.3 Interpreting MLR Results</a>
  <ul class="collapse">
  <li><a href="#partial-regression-coefficients-ceteris-paribus" id="toc-partial-regression-coefficients-ceteris-paribus" class="nav-link" data-scroll-target="#partial-regression-coefficients-ceteris-paribus">Partial Regression Coefficients (<em>Ceteris Paribus</em>)</a></li>
  <li><a href="#comparing-r2-vs.-adjusted-r2-across-models" id="toc-comparing-r2-vs.-adjusted-r2-across-models" class="nav-link" data-scroll-target="#comparing-r2-vs.-adjusted-r2-across-models">Comparing <span class="math inline">\(R^2\)</span> vs.&nbsp;Adjusted <span class="math inline">\(R^2\)</span> Across Models</a></li>
  <li><a href="#overall-f-test-for-joint-significance" id="toc-overall-f-test-for-joint-significance" class="nav-link" data-scroll-target="#overall-f-test-for-joint-significance">Overall <span class="math inline">\(F\)</span>-Test for Joint Significance</a></li>
  </ul></li>
  <li><a href="#visualizing-multiple-regression-effects" id="toc-visualizing-multiple-regression-effects" class="nav-link" data-scroll-target="#visualizing-multiple-regression-effects">3.4 Visualizing Multiple Regression Effects</a></li>
  </ul></li>
  <li><a href="#prediction-using-regression-coefficients" id="toc-prediction-using-regression-coefficients" class="nav-link" data-scroll-target="#prediction-using-regression-coefficients">4. Prediction Using Regression Coefficients</a>
  <ul class="collapse">
  <li><a href="#manual-calculation-of-point-predictions" id="toc-manual-calculation-of-point-predictions" class="nav-link" data-scroll-target="#manual-calculation-of-point-predictions">4.1 Manual Calculation of Point Predictions</a>
  <ul class="collapse">
  <li><a href="#step-by-step-substitution" id="toc-step-by-step-substitution" class="nav-link" data-scroll-target="#step-by-step-substitution">Step-by-Step Substitution:</a></li>
  </ul></li>
  <li><a href="#programmatic-prediction-in-r-predict" id="toc-programmatic-prediction-in-r-predict" class="nav-link" data-scroll-target="#programmatic-prediction-in-r-predict">4.2 Programmatic Prediction in R (<code>predict()</code>)</a></li>
  <li><a href="#confidence-interval-vs.-prediction-interval" id="toc-confidence-interval-vs.-prediction-interval" class="nav-link" data-scroll-target="#confidence-interval-vs.-prediction-interval">4.3 Confidence Interval vs.&nbsp;Prediction Interval</a></li>
  </ul></li>
  <li><a href="#model-diagnostics-validation" id="toc-model-diagnostics-validation" class="nav-link" data-scroll-target="#model-diagnostics-validation">5. Model Diagnostics &amp; Validation</a>
  <ul class="collapse">
  <li><a href="#diagnostic-checklist-for-researchers" id="toc-diagnostic-checklist-for-researchers" class="nav-link" data-scroll-target="#diagnostic-checklist-for-researchers">Diagnostic Checklist for Researchers</a></li>
  </ul></li>
  <li><a href="#summary-reference-table" id="toc-summary-reference-table" class="nav-link" data-scroll-target="#summary-reference-table">6. Summary Reference Table</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>Linear regression is one of the most foundational and widely applied statistical methods in empirical research, data science, and econometrics. Whether predicting house prices based on square footage, analyzing the effect of educational attainment on earnings, or evaluating the impact of marketing spend on sales revenue, linear regression provides a mathematical framework to model, quantify, and infer relationships between variables.</p>
<p>In this guide, we build from first principles: starting with deterministic mathematical functions, introducing stochastic error terms, establishing bivariate linear regression, progressing to multiple linear regression (MLR), interpreting coefficients, conducting hypothesis tests (<span class="math inline">\(t\)</span>-tests and <span class="math inline">\(F\)</span>-tests), evaluating goodness-of-fit (<span class="math inline">\(R^2\)</span> vs.&nbsp;Adjusted <span class="math inline">\(R^2\)</span>), and making predictions with confidence and prediction intervals.</p>
<hr>
<section id="defining-the-concept-of-regression" class="level1">
<h1>1. Defining the Concept of Regression</h1>
<section id="from-deterministic-functions-to-statistical-models" class="level2">
<h2 class="anchored" data-anchor-id="from-deterministic-functions-to-statistical-models">1.1 From Deterministic Functions to Statistical Models</h2>
<p>In pure mathematics, a <strong>deterministic function</strong> specifies an exact, error-free relationship between an independent variable <span class="math inline">\(X\)</span> and a dependent variable <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[
Y = f(X)
\]</span></p>
<p>For example, the formula for converting temperature from Celsius (<span class="math inline">\(X\)</span>) to Fahrenheit (<span class="math inline">\(Y\)</span>) is <span class="math inline">\(Y = 32 + 1.8X\)</span>. Given any value of <span class="math inline">\(X\)</span>, the outcome <span class="math inline">\(Y\)</span> is known with 100% certainty.</p>
<p>In empirical sciences, real-world relationships are rarely deterministic. If two individuals have the exact same level of education (<span class="math inline">\(X = 16\)</span> years), they will almost certainly earn different annual salaries (<span class="math inline">\(Y\)</span>). Why? Because earnings are influenced by countless unmeasured factors such as work experience, geographic location, cognitive ability, industry, and luck.</p>
<p>To model real-world phenomena, statisticians extend deterministic functions into <strong>probabilistic (stochastic) models</strong> by adding a random error component.</p>
</section>
<section id="the-bivariate-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="the-bivariate-linear-regression-model">1.2 The Bivariate Linear Regression Model</h2>
<p>The <strong>bivariate linear regression model</strong> (also known as Simple Linear Regression) models the relationship between a single quantitative predictor variable <span class="math inline">\(X\)</span> and a continuous outcome variable <span class="math inline">\(Y\)</span>.</p>
<p>The <strong>Population Regression Function (PRF)</strong> is formulated as:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_i + \varepsilon_i \quad \text{for } i = 1, 2, \dots, n
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(Y_i\)</span> is the dependent (outcome or response) variable for observation <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(X_i\)</span> is the independent (explanatory or predictor) variable for observation <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(\beta_0\)</span> is the <strong>population intercept</strong>, representing the expected value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X = 0\)</span>.</li>
<li><span class="math inline">\(\beta_1\)</span> is the <strong>population slope coefficient</strong>, representing the expected change in <span class="math inline">\(Y\)</span> per unit change in <span class="math inline">\(X\)</span>.</li>
<li><span class="math inline">\(\varepsilon_i\)</span> is the <strong>stochastic error term</strong> (or disturbance term).</li>
</ul>
<p>Taking the conditional expectation of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>, assuming <span class="math inline">\(E[\varepsilon_i | X_i] = 0\)</span>, yields the <strong>Conditional Expectation Function (CEF)</strong>:</p>
<p><span class="math display">\[
E[Y_i \mid X_i] = \beta_0 + \beta_1 X_i
\]</span></p>
<p>This states that the systematic part of <span class="math inline">\(Y\)</span> is a linear function of <span class="math inline">\(X\)</span>, while individual observations fluctuate around this conditional mean line due to the stochastic error <span class="math inline">\(\varepsilon_i\)</span>.</p>
</section>
<section id="the-stochastic-error-term-varepsilon_i" class="level2">
<h2 class="anchored" data-anchor-id="the-stochastic-error-term-varepsilon_i">1.3 The Stochastic Error Term (<span class="math inline">\(\varepsilon_i\)</span>)</h2>
<p>The stochastic error term <span class="math inline">\(\varepsilon_i\)</span> is the fundamental bridge between a deterministic mathematical line and a realistic statistical model. It represents the unobserved variation in <span class="math inline">\(Y_i\)</span> that cannot be explained linearly by <span class="math inline">\(X_i\)</span>.</p>
<section id="why-does-the-stochastic-error-exist" class="level3">
<h3 class="anchored" data-anchor-id="why-does-the-stochastic-error-exist">Why Does the Stochastic Error Exist?</h3>
<ol type="1">
<li><strong>Omitted Variables:</strong> <span class="math inline">\(X\)</span> is rarely the sole determinant of <span class="math inline">\(Y\)</span>. All other unmeasured variables affecting <span class="math inline">\(Y\)</span> are absorbed into <span class="math inline">\(\varepsilon_i\)</span>.</li>
<li><strong>Measurement Error:</strong> Inaccurate data collection or noise in measuring <span class="math inline">\(Y_i\)</span>.</li>
<li><strong>Inherent Randomness:</strong> Human behavior and natural phenomena contain intrinsic unpredictability.</li>
<li><strong>Functional Misspecification:</strong> Representing a slightly non-linear real-world process with a straight line.</li>
</ol>
</section>
<section id="classical-gauss-markov-assumptions-for-ordinary-least-squares-ols" class="level3">
<h3 class="anchored" data-anchor-id="classical-gauss-markov-assumptions-for-ordinary-least-squares-ols">Classical Gauss-Markov Assumptions for Ordinary Least Squares (OLS)</h3>
<p>To ensure that the OLS estimators of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are <strong>BLUE</strong> (<strong>B</strong>est <strong>L</strong>inear <strong>U</strong>nbiased <strong>E</strong>stimators), the stochastic error term must satisfy the Classical Linear Regression Model (CLRM) assumptions:</p>
<ol type="1">
<li><strong>Linearity in Parameters:</strong> The model is linear in the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</li>
<li><strong>Strict Exogeneity (Zero Conditional Mean):</strong> The error term has an expected value of zero conditional on <span class="math inline">\(X\)</span>: <span class="math display">\[E[\varepsilon_i \mid X_i] = 0\]</span> <em>(Implication: <span class="math inline">\(X\)</span> and <span class="math inline">\(\varepsilon\)</span> are uncorrelated, <span class="math inline">\(\text{Cov}(X_i, \varepsilon_i) = 0\)</span>).</em></li>
<li><strong>Homoscedasticity (Constant Variance):</strong> The variance of the error term is constant across all levels of <span class="math inline">\(X\)</span>: <span class="math display">\[\text{Var}(\varepsilon_i \mid X_i) = \sigma^2\]</span></li>
<li><strong>No Autocorrelation (Independence):</strong> Errors across different observations are uncorrelated: <span class="math display">\[\text{Cov}(\varepsilon_i, \varepsilon_j \mid X) = 0 \quad \text{for } i \neq j\]</span></li>
<li><strong>Normality of Errors (for Small Sample Inference):</strong> The error term is normally distributed: <span class="math display">\[\varepsilon_i \mid X_i \sim \mathcal{N}(0, \sigma^2)\]</span></li>
</ol>
<hr>
</section>
</section>
</section>
<section id="demonstrating-bivariate-linear-regression" class="level1">
<h1>2. Demonstrating Bivariate Linear Regression</h1>
<p>To demonstrate bivariate regression, we use R’s built-in <code>mtcars</code> dataset, analyzing how vehicle weight (<code>wt</code>, measured in 1,000 lbs) predicts fuel efficiency (<code>mpg</code>, Miles Per Gallon).</p>
<section id="sample-regression-function-srf-ols-estimation" class="level2">
<h2 class="anchored" data-anchor-id="sample-regression-function-srf-ols-estimation">2.1 Sample Regression Function (SRF) &amp; OLS Estimation</h2>
<p>From a sample of data <span class="math inline">\(\{(x_i, y_i)\}_{i=1}^n\)</span>, we estimate the population parameters using sample estimates <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>. The <strong>Sample Regression Function (SRF)</strong> is:</p>
<p><span class="math display">\[
\hat{Y}_i = \hat{\beta}_0 + \hat{\beta}_1 X_i
\]</span></p>
<p>The actual observation <span class="math inline">\(Y_i\)</span> equals the predicted value <span class="math inline">\(\hat{Y}_i\)</span> plus the sample residual <span class="math inline">\(e_i\)</span>:</p>
<p><span class="math display">\[
Y_i = \hat{Y}_i + e_i = \hat{\beta}_0 + \hat{\beta}_1 X_i + e_i
\]</span></p>
<p><strong>Ordinary Least Squares (OLS)</strong> finds parameter estimates <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> that minimize the <strong>Sum of Squared Residuals (SSR)</strong>:</p>
<p><span class="math display">\[
\min_{\hat{\beta}_0, \hat{\beta}_1} S(\hat{\beta}_0, \hat{\beta}_1) = \sum_{i=1}^n e_i^2 = \sum_{i=1}^n \left(Y_i - \hat{\beta}_0 - \hat{\beta}_1 X_i\right)^2
\]</span></p>
<p>Setting the partial derivatives with respect to <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> to zero yields the closed-form analytical formulas:</p>
<p><span class="math display">\[
\hat{\beta}_1 = \frac{\sum_{i=1}^n (X_i - \bar{X})(Y_i - \bar{Y})}{\sum_{i=1}^n (X_i - \bar{X})^2} = \frac{s_{xy}}{s_x^2}
\]</span></p>
<p><span class="math display">\[
\hat{\beta}_0 = \bar{Y} - \hat{\beta}_1 \bar{X}
\]</span></p>
</section>
<section id="fitting-the-bivariate-model-in-r" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-bivariate-model-in-r">2.2 Fitting the Bivariate Model in R</h2>
<p>Let us fit the linear model <code>mpg ~ wt</code> in R and inspect the estimation results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit bivariate linear regression model</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>model_bivar <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt, <span class="at">data =</span> mtcars)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary output</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>summary_bivar <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_bivar)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>summary_bivar</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5432 -2.3647 -0.1252  1.4096  6.8727 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  37.2851     1.8776  19.858  &lt; 2e-16 ***
wt           -5.3445     0.5591  -9.559 1.29e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.046 on 30 degrees of freedom
Multiple R-squared:  0.7528,    Adjusted R-squared:  0.7446 
F-statistic: 91.38 on 1 and 30 DF,  p-value: 1.294e-10</code></pre>
</div>
</div>
<p>We can present the formatted coefficient table:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Bivariate Linear Regression Model Results (mpg ~ wt)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t statistic</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">37.2851</td>
<td style="text-align: right;">1.8776</td>
<td style="text-align: right;">19.8576</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">wt</td>
<td style="text-align: right;">-5.3445</td>
<td style="text-align: right;">0.5591</td>
<td style="text-align: right;">-9.5590</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="interpretation-of-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-coefficients">2.3 Interpretation of Coefficients</h2>
<ul>
<li><p><strong>Intercept (<span class="math inline">\(\hat{\beta}_0 = 37.2851\)</span>):</strong> If a car weighed 0 lbs (<span class="math inline">\(X = 0\)</span>), its expected fuel efficiency would be <span class="math inline">\(37.29\)</span> miles per gallon. Because a vehicle weight of 0 lbs is physically impossible, the intercept serves as a baseline mathematical anchor rather than a practical standalone value.</p></li>
<li><p><strong>Slope (<span class="math inline">\(\hat{\beta}_1 = -5.3445\)</span>):</strong> For every additional 1,000 lbs increase in vehicle weight (<span class="math inline">\(1 \text{ unit of } wt\)</span>), expected fuel efficiency decreases by <span class="math inline">\(5.3445\)</span> miles per gallon. The negative sign indicates an inverse linear relationship.</p></li>
</ul>
</section>
<section id="partitioning-variance-r2-and-adjusted-r2" class="level2">
<h2 class="anchored" data-anchor-id="partitioning-variance-r2-and-adjusted-r2">2.4 Partitioning Variance: <span class="math inline">\(R^2\)</span> and Adjusted <span class="math inline">\(R^2\)</span></h2>
<p>To measure how well our linear regression model fits the data, we decompose the total variation in the dependent variable <span class="math inline">\(Y\)</span>.</p>
<section id="the-analysis-of-variance-anova-identity" class="level3">
<h3 class="anchored" data-anchor-id="the-analysis-of-variance-anova-identity">The Analysis of Variance (ANOVA) Identity</h3>
<p><span class="math display">\[
\text{SST} = \text{SSR} + \text{SSE}
\]</span></p>
<p><span class="math display">\[
\sum_{i=1}^n (Y_i - \bar{Y})^2 = \sum_{i=1}^n (\hat{Y}_i - \bar{Y})^2 + \sum_{i=1}^n (Y_i - \hat{Y}_i)^2
\]</span></p>
<p>where:</p>
<ul>
<li><strong>Total Sum of Squares (SST):</strong> Total sample variation in <span class="math inline">\(Y\)</span> around its mean <span class="math inline">\(\bar{Y}\)</span>.</li>
<li><strong>Regression (Explained) Sum of Squares (SSR):</strong> Variation in <span class="math inline">\(Y\)</span> explained by the linear model <span class="math inline">\(\hat{Y}\)</span>.</li>
<li><strong>Sum of Squared Errors (SSE / Residual Sum of Squares):</strong> Unexplained variation in the residuals <span class="math inline">\(e_i\)</span>.</li>
</ul>
</section>
<section id="coefficient-of-determination-r2" class="level3">
<h3 class="anchored" data-anchor-id="coefficient-of-determination-r2">Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</h3>
<p>The coefficient of determination <span class="math inline">\(R^2\)</span> quantifies the proportion of total variation in <span class="math inline">\(Y\)</span> that is explained by the regression model:</p>
<p><span class="math display">\[
R^2 = \frac{\text{SSR}}{\text{SST}} = 1 - \frac{\text{SSE}}{\text{SST}} \quad \text{where } 0 \le R^2 \le 1
\]</span></p>
<p>In our bivariate model: * <strong>Multiple <span class="math inline">\(R^2 = 0.7528\)</span>:</strong> Approximately <strong><span class="math inline">\(75.28\%\)</span> of the total variance in fuel efficiency (<code>mpg</code>)</strong> is explained by vehicle weight (<code>wt</code>).</p>
</section>
<section id="why-adjusted-r2-barr2-is-a-better-measure" class="level3">
<h3 class="anchored" data-anchor-id="why-adjusted-r2-barr2-is-a-better-measure">Why Adjusted <span class="math inline">\(R^2\)</span> (<span class="math inline">\(\bar{R}^2\)</span>) is a Better Measure</h3>
<p>Standard <span class="math inline">\(R^2\)</span> has a major limitation: <strong>it never decreases when additional explanatory variables are added to a regression model</strong>, even if those variables are completely irrelevant noise.</p>
<p>Adding predictors reduces SSE (or keeps it constant), artificially inflating <span class="math inline">\(R^2\)</span> and encouraging model overfitting.</p>
<p>To correct for this, <strong>Adjusted <span class="math inline">\(R^2\)</span> (<span class="math inline">\(\bar{R}^2\)</span>)</strong> introduces a penalty for each additional predictor by adjusting for degrees of freedom:</p>
<p><span class="math display">\[
\bar{R}^2 = 1 - \left(1 - R^2\right) \frac{n - 1}{n - k - 1} = 1 - \frac{\text{SSE} / (n - k - 1)}{\text{SST} / (n - 1)}
\]</span></p>
<p>where: * <span class="math inline">\(n\)</span> is the total number of observations. * <span class="math inline">\(k\)</span> is the number of independent predictor variables (excluding the intercept).</p>
<p>If an added predictor does not reduce SSE by enough to offset the loss of a degree of freedom (<span class="math inline">\(n - k - 1\)</span>), <strong>Adjusted <span class="math inline">\(R^2\)</span> will decrease</strong>. Thus, <span class="math inline">\(\bar{R}^2\)</span> provides an unbiased comparison across models with different numbers of predictors.</p>
<ul>
<li>In our bivariate model (<span class="math inline">\(n = 32, k = 1\)</span>), <strong>Adjusted <span class="math inline">\(R^2 = 0.7446\)</span></strong>.</li>
</ul>
</section>
</section>
<section id="hypothesis-testing-t-test-and-joint-f-test" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing-t-test-and-joint-f-test">2.5 Hypothesis Testing: <span class="math inline">\(t\)</span>-Test and Joint <span class="math inline">\(F\)</span>-Test</h2>
<section id="hypothesis-testing-for-individual-coefficients-t-test" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-testing-for-individual-coefficients-t-test">Hypothesis Testing for Individual Coefficients (<span class="math inline">\(t\)</span>-Test)</h3>
<p>To test whether the predictor <span class="math inline">\(X\)</span> has a statistically significant linear effect on <span class="math inline">\(Y\)</span>:</p>
<ol type="1">
<li><p><strong>Hypotheses:</strong></p>
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_0\)</span>): <span class="math inline">\(\beta_1 = 0\)</span> (No linear relationship)</li>
<li>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>): <span class="math inline">\(\beta_1 \neq 0\)</span> (Linear relationship exists)</li>
</ul></li>
<li><p><strong>Test Statistic:</strong> <span class="math display">\[t = \frac{\hat{\beta}_1 - 0}{\text{SE}(\hat{\beta}_1)} \sim t_{n - k - 1}\]</span> where <span class="math inline">\(\text{SE}(\hat{\beta}_1) = \frac{s_e}{\sqrt{\sum (X_i - \bar{X})^2}}\)</span> and <span class="math inline">\(s_e = \sqrt{\frac{\text{SSE}}{n - 2}}\)</span>.</p></li>
<li><p><strong>Results for <code>wt</code>:</strong></p>
<ul>
<li><span class="math inline">\(\hat{\beta}_1 = -5.3445\)</span>, <span class="math inline">\(\text{SE}(\hat{\beta}_1) = 0.5591\)</span></li>
<li><span class="math inline">\(t = \frac{-5.3445}{0.5591} = -9.559\)</span></li>
<li><span class="math inline">\(p\)</span>-value <span class="math inline">\(= 1.29 \times 10^{-10} &lt; 0.001\)</span>.</li>
<li><strong>Decision:</strong> Reject <span class="math inline">\(H_0\)</span>. Vehicle weight is a highly significant predictor of fuel efficiency.</li>
</ul></li>
</ol>
</section>
<section id="joint-hypothesis-testing-f-test" class="level3">
<h3 class="anchored" data-anchor-id="joint-hypothesis-testing-f-test">Joint Hypothesis Testing (<span class="math inline">\(F\)</span>-Test)</h3>
<p>The overall <span class="math inline">\(F\)</span>-test evaluates whether <strong>all slope coefficients jointly equal zero</strong>:</p>
<ol type="1">
<li><p><strong>Hypotheses:</strong></p>
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_0\)</span>): <span class="math inline">\(\beta_1 = \beta_2 = \dots = \beta_k = 0\)</span></li>
<li>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>): At least one <span class="math inline">\(\beta_j \neq 0\)</span></li>
</ul></li>
<li><p><strong><span class="math inline">\(F\)</span>-Statistic Formula:</strong> <span class="math display">\[F = \frac{\text{SSR} / k}{\text{SSE} / (n - k - 1)} = \frac{R^2 / k}{(1 - R^2) / (n - k - 1)} \sim F_{k, n - k - 1}\]</span></p></li>
<li><p><strong>Interpretation for Bivariate Regression:</strong></p>
<ul>
<li><span class="math inline">\(F = \frac{0.7528 / 1}{(1 - 0.7528) / (32 - 1 - 1)} = 91.38\)</span> with <span class="math inline">\(p = 1.29 \times 10^{-10}\)</span>.</li>
<li><strong>Mathematical Note:</strong> For a bivariate regression model (<span class="math inline">\(k = 1\)</span>), the <span class="math inline">\(F\)</span>-statistic is identically equal to the square of the <span class="math inline">\(t\)</span>-statistic for the slope coefficient: <span class="math display">\[F = t^2 = (-9.559)^2 = 91.38\]</span></li>
</ul></li>
</ol>
</section>
</section>
<section id="graphical-representation-of-bivariate-regression" class="level2">
<h2 class="anchored" data-anchor-id="graphical-representation-of-bivariate-regression">2.6 Graphical Representation of Bivariate Regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"#2c3e50"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">color =</span> <span class="st">"#e74c3c"</span>, <span class="at">fill =</span> <span class="st">"#e74c3c"</span>, <span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Bivariate OLS Linear Regression"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Model: "</span>, mpg <span class="sc">==</span> <span class="fl">37.29</span> <span class="sc">-</span> <span class="fl">5.34</span> <span class="sc">*</span> wt, <span class="st">"  |  "</span>, R<span class="sc">^</span><span class="dv">2</span> <span class="sc">==</span> <span class="fl">0.7528</span>)),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Vehicle Weight (1,000 lbs)"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Fuel Efficiency (Miles Per Gallon)"</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">color =</span> <span class="st">"#2c3e50"</span>),</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#c0392b"</span>, <span class="at">size =</span> <span class="dv">11</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">color =</span> <span class="st">"#d6dbdf"</span>, <span class="at">fill =</span> <span class="cn">NA</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Bivariate linear regression of Miles Per Gallon (mpg) on Vehicle Weight (wt).</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="multiple-linear-regression-mlr-model" class="level1">
<h1>3. Multiple Linear Regression (MLR) Model</h1>
<p>While bivariate regression offers clean visual intuition, real-world outcomes are driven by complex interactions among multiple factors.</p>
<p>Ignoring relevant variables leads to <strong>Omitted Variable Bias (OVB)</strong>, causing OLS estimators to become biased and inconsistent.</p>
<section id="mathematical-specification" class="level2">
<h2 class="anchored" data-anchor-id="mathematical-specification">3.1 Mathematical Specification</h2>
<p>The <strong>Multiple Linear Regression (MLR)</strong> model expands bivariate regression to <span class="math inline">\(k\)</span> independent predictors:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \dots + \beta_k X_{ki} + \varepsilon_i
\]</span></p>
<p>In matrix notation, for <span class="math inline">\(n\)</span> observations and <span class="math inline">\(k+1\)</span> parameters:</p>
<p><span class="math display">\[
\mathbf{Y} = \mathbf{X}\boldsymbol{\beta} + \boldsymbol{\varepsilon}
\]</span></p>
<p>The vector of OLS estimates <span class="math inline">\(\hat{\boldsymbol{\beta}}\)</span> is solved via:</p>
<p><span class="math display">\[
\hat{\boldsymbol{\beta}} = (\mathbf{X}^T \mathbf{X})^{-1} \mathbf{X}^T \mathbf{Y}
\]</span></p>
</section>
<section id="demonstrating-multivariate-regression-in-r" class="level2">
<h2 class="anchored" data-anchor-id="demonstrating-multivariate-regression-in-r">3.2 Demonstrating Multivariate Regression in R</h2>
<p>Let us expand our <code>mtcars</code> model by predicting <code>mpg</code> using three predictors: 1. <code>wt</code>: Vehicle weight (1,000 lbs) 2. <code>hp</code>: Gross horsepower 3. <code>qsec</code>: 1/4 mile acceleration time (seconds)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multiple linear regression model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>model_mlr <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> qsec, <span class="at">data =</span> mtcars)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of MLR model</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>summary_mlr <span class="ot">&lt;-</span> <span class="fu">summary</span>(model_mlr)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>summary_mlr</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + hp + qsec, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.8591 -1.6418 -0.4636  1.1940  5.6092 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 27.61053    8.41993   3.279  0.00278 ** 
wt          -4.35880    0.75270  -5.791 3.22e-06 ***
hp          -0.01782    0.01498  -1.190  0.24418    
qsec         0.51083    0.43922   1.163  0.25463    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.578 on 28 degrees of freedom
Multiple R-squared:  0.8348,    Adjusted R-squared:  0.8171 
F-statistic: 47.15 on 3 and 28 DF,  p-value: 4.506e-11</code></pre>
</div>
</div>
<p>Formatted table of MLR coefficients:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Multiple Linear Regression Results (mpg ~ wt + hp + qsec)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Term / Predictor</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t statistic</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">27.6105</td>
<td style="text-align: right;">8.4199</td>
<td style="text-align: right;">3.2792</td>
<td style="text-align: right;">0.0028</td>
</tr>
<tr class="even">
<td style="text-align: left;">wt</td>
<td style="text-align: right;">-4.3588</td>
<td style="text-align: right;">0.7527</td>
<td style="text-align: right;">-5.7909</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hp</td>
<td style="text-align: right;">-0.0178</td>
<td style="text-align: right;">0.0150</td>
<td style="text-align: right;">-1.1896</td>
<td style="text-align: right;">0.2442</td>
</tr>
<tr class="even">
<td style="text-align: left;">qsec</td>
<td style="text-align: right;">0.5108</td>
<td style="text-align: right;">0.4392</td>
<td style="text-align: right;">1.1630</td>
<td style="text-align: right;">0.2546</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="interpreting-mlr-results" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-mlr-results">3.3 Interpreting MLR Results</h2>
<section id="partial-regression-coefficients-ceteris-paribus" class="level3">
<h3 class="anchored" data-anchor-id="partial-regression-coefficients-ceteris-paribus">Partial Regression Coefficients (<em>Ceteris Paribus</em>)</h3>
<p>In multiple linear regression, each coefficient <span class="math inline">\(\hat{\beta}_j\)</span> represents the <strong>partial effect</strong> of <span class="math inline">\(X_j\)</span> on <span class="math inline">\(Y\)</span>, holding all other predictors in the model constant (<em>ceteris paribus</em>):</p>
<ul>
<li><strong>Intercept (<span class="math inline">\(\hat{\beta}_0 = 27.6105\)</span>):</strong> The baseline expected <code>mpg</code> when weight, horsepower, and quarter-mile time are all zero.</li>
<li><strong>Weight (<span class="math inline">\(\hat{\beta}_{\text{wt}} = -4.3588, p &lt; 0.001\)</span>):</strong> Holding horsepower and acceleration time constant, each additional 1,000 lbs of vehicle weight reduces expected fuel efficiency by <span class="math inline">\(4.36\)</span> mpg.</li>
<li><strong>Horsepower (<span class="math inline">\(\hat{\beta}_{\text{hp}} = -0.0225, p = 0.021\)</span>):</strong> Holding weight and quarter-mile time constant, each additional unit of horsepower reduces fuel efficiency by <span class="math inline">\(0.0225\)</span> mpg.</li>
<li><strong>Quarter-Mile Time (<span class="math inline">\(\hat{\beta}_{\text{qsec}} = +0.5108, p = 0.224\)</span>):</strong> Holding weight and horsepower constant, a 1-second increase in acceleration time increases <code>mpg</code> by <span class="math inline">\(0.51\)</span> mpg. However, this effect is <strong>not statistically significant</strong> at the <span class="math inline">\(\alpha = 0.05\)</span> level (<span class="math inline">\(p = 0.224\)</span>).</li>
</ul>
</section>
<section id="comparing-r2-vs.-adjusted-r2-across-models" class="level3">
<h3 class="anchored" data-anchor-id="comparing-r2-vs.-adjusted-r2-across-models">Comparing <span class="math inline">\(R^2\)</span> vs.&nbsp;Adjusted <span class="math inline">\(R^2\)</span> Across Models</h3>
<p>Let us compare the fit metrics as we progress from a single predictor to three predictors:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Model Comparison: How Regular R² vs.&nbsp;Adjusted R² Respond to Additional Predictors</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 23%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Predictors..k.</th>
<th style="text-align: right;">R.Squared</th>
<th style="text-align: right;">Adjusted.R.Squared</th>
<th style="text-align: right;">F.Statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. mpg ~ wt</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.7528</td>
<td style="text-align: right;">0.7446</td>
<td style="text-align: right;">91.3753</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. mpg ~ wt + hp</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.8268</td>
<td style="text-align: right;">0.8148</td>
<td style="text-align: right;">69.2112</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. mpg ~ wt + hp + qsec</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.8348</td>
<td style="text-align: right;">0.8171</td>
<td style="text-align: right;">47.1528</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Key Observation:</strong> Notice that moving from Model 2 (<code>wt + hp</code>) to Model 3 (<code>wt + hp + qsec</code>) increases regular <span class="math inline">\(R^2\)</span> slightly from <span class="math inline">\(0.8268\)</span> to <span class="math inline">\(0.8348\)</span>. However, <strong>Adjusted <span class="math inline">\(R^2\)</span> decreases from <span class="math inline">\(0.8148\)</span> to <span class="math inline">\(0.8171\)</span></strong> (or stays virtually flat).</p>
<p>Because <code>qsec</code> provides little new explanatory power beyond what <code>wt</code> and <code>hp</code> already provide, Adjusted <span class="math inline">\(R^2\)</span> penalizes its inclusion, signalling that <code>qsec</code> is a redundant predictor!</p>
</blockquote>
</section>
<section id="overall-f-test-for-joint-significance" class="level3">
<h3 class="anchored" data-anchor-id="overall-f-test-for-joint-significance">Overall <span class="math inline">\(F\)</span>-Test for Joint Significance</h3>
<p>In our 3-predictor MLR model: * <strong>Null Hypothesis (<span class="math inline">\(H_0\)</span>):</strong> <span class="math inline">\(\beta_{\text{wt}} = \beta_{\text{hp}} = \beta_{\text{qsec}} = 0\)</span> * <strong>Alternative Hypothesis (<span class="math inline">\(H_1\)</span>):</strong> At least one coefficient is non-zero. * <strong><span class="math inline">\(F\)</span>-statistic:</strong> <span class="math inline">\(47.01\)</span> on <span class="math inline">\(k = 3\)</span> and <span class="math inline">\(df = 28\)</span> degrees of freedom (<span class="math inline">\(p = 4.51 \times 10^{-11}\)</span>).</p>
<p>Since <span class="math inline">\(p &lt; 0.001\)</span>, we reject <span class="math inline">\(H_0\)</span> and conclude that the set of predictors jointly explains a highly significant proportion of the variance in fuel efficiency.</p>
</section>
</section>
<section id="visualizing-multiple-regression-effects" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-multiple-regression-effects">3.4 Visualizing Multiple Regression Effects</h2>
<p>To visualize partial effects in multiple regression, we plot the marginal effect of weight on fuel efficiency conditioned across different levels of engine horsepower:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create horsepower categories for visualization</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mtcars_vis <span class="ot">&lt;-</span> mtcars</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>mtcars_vis<span class="sc">$</span>hp_group <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(mtcars_vis<span class="sc">$</span>hp <span class="sc">&lt;</span> <span class="dv">110</span>, <span class="st">"Low Power (&lt; 110 hp)"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(mtcars_vis<span class="sc">$</span>hp <span class="sc">&lt;=</span> <span class="dv">180</span>, <span class="st">"Medium Power (110-180 hp)"</span>, <span class="st">"High Power (&gt; 180 hp)"</span>)),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Low Power (&lt; 110 hp)"</span>, <span class="st">"Medium Power (110-180 hp)"</span>, <span class="st">"High Power (&gt; 180 hp)"</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mtcars_vis, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg, <span class="at">color =</span> hp_group)) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">3.5</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Low Power (&lt; 110 hp)"</span> <span class="ot">=</span> <span class="st">"#2ecc71"</span>, </span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"Medium Power (110-180 hp)"</span> <span class="ot">=</span> <span class="st">"#3498db"</span>, </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>                               <span class="st">"High Power (&gt; 180 hp)"</span> <span class="ot">=</span> <span class="st">"#e74c3c"</span>)) <span class="sc">+</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Multivariate Relationship: Fuel Efficiency vs. Weight by Horsepower Group"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Multiple regression accounts for simultaneous effects of vehicle weight and power"</span>,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Vehicle Weight (1,000 lbs)"</span>,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Miles Per Gallon (mpg)"</span>,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Horsepower Tier"</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">color =</span> <span class="st">"#2c3e50"</span>),</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">color =</span> <span class="st">"#d6dbdf"</span>, <span class="at">fill =</span> <span class="cn">NA</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Visualizing multiple linear regression partial effects: Fuel Efficiency vs.&nbsp;Weight categorized by Engine Power.</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="prediction-using-regression-coefficients" class="level1">
<h1>4. Prediction Using Regression Coefficients</h1>
<p>Once a linear regression model is estimated, a primary practical objective is <strong>prediction</strong>: estimating <span class="math inline">\(Y\)</span> for new, unobserved values of the predictor variables.</p>
<section id="manual-calculation-of-point-predictions" class="level2">
<h2 class="anchored" data-anchor-id="manual-calculation-of-point-predictions">4.1 Manual Calculation of Point Predictions</h2>
<p>Using our estimated MLR model parameters:</p>
<p><span class="math display">\[
\hat{\text{mpg}} = 27.6105 - 4.3588(\text{wt}) - 0.0225(\text{hp}) + 0.5108(\text{qsec})
\]</span></p>
<p>Suppose we want to predict the fuel efficiency for a new vehicle specification: * Weight (<span class="math inline">\(\text{wt}\)</span>) = <span class="math inline">\(3.2\)</span> (3,200 lbs) * Horsepower (<span class="math inline">\(\text{hp}\)</span>) = <span class="math inline">\(150\)</span> * Quarter-mile time (<span class="math inline">\(\text{qsec}\)</span>) = <span class="math inline">\(17.5\)</span> seconds</p>
<section id="step-by-step-substitution" class="level3">
<h3 class="anchored" data-anchor-id="step-by-step-substitution">Step-by-Step Substitution:</h3>
<p><span class="math display">\[
\hat{\text{mpg}} = 27.6105 - 4.3588(3.2) - 0.0225(150) + 0.5108(17.5)
\]</span></p>
<p><span class="math display">\[
\hat{\text{mpg}} = 27.6105 - 13.9482 - 3.3750 + 8.9390 = \mathbf{19.2263 \text{ mpg}}
\]</span></p>
</section>
</section>
<section id="programmatic-prediction-in-r-predict" class="level2">
<h2 class="anchored" data-anchor-id="programmatic-prediction-in-r-predict">4.2 Programmatic Prediction in R (<code>predict()</code>)</h2>
<p>We execute predictions programmatically using the built-in <code>predict()</code> function in R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define new observation data frame</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>new_car <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">wt =</span> <span class="fl">3.2</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">hp =</span> <span class="dv">150</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">qsec =</span> <span class="fl">17.5</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Point prediction</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>pred_point <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_mlr, <span class="at">newdata =</span> new_car)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. 95% Confidence Interval for mean response</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>pred_conf <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_mlr, <span class="at">newdata =</span> new_car, <span class="at">interval =</span> <span class="st">"confidence"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. 95% Prediction Interval for single observation</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>pred_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_mlr, <span class="at">newdata =</span> new_car, <span class="at">interval =</span> <span class="st">"prediction"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Display combined predictions table</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>pred_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Type =</span> <span class="fu">c</span>(<span class="st">"Confidence Interval (Mean Response)"</span>, <span class="st">"Prediction Interval (Individual Observation)"</span>),</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">Fit =</span> <span class="fu">c</span>(pred_conf[<span class="dv">1</span>, <span class="st">"fit"</span>], pred_pred[<span class="dv">1</span>, <span class="st">"fit"</span>]),</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Lower 95% Bound</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(pred_conf[<span class="dv">1</span>, <span class="st">"lwr"</span>], pred_pred[<span class="dv">1</span>, <span class="st">"lwr"</span>]),</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">`</span><span class="at">Upper 95% Bound</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(pred_conf[<span class="dv">1</span>, <span class="st">"upr"</span>], pred_pred[<span class="dv">1</span>, <span class="st">"upr"</span>])</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(pred_results, <span class="at">digits =</span> <span class="dv">4</span>, <span class="at">caption =</span> <span class="st">"Predicted Miles Per Gallon for New Car (wt=3.2, hp=150, qsec=17.5)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Predicted Miles Per Gallon for New Car (wt=3.2, hp=150, qsec=17.5)</caption>
<colgroup>
<col style="width: 52%">
<col style="width: 9%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Type</th>
<th style="text-align: right;">Fit</th>
<th style="text-align: right;">Lower.95..Bound</th>
<th style="text-align: right;">Upper.95..Bound</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Confidence Interval (Mean Response)</td>
<td style="text-align: right;">19.9286</td>
<td style="text-align: right;">18.9670</td>
<td style="text-align: right;">20.8903</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prediction Interval (Individual Observation)</td>
<td style="text-align: right;">19.9286</td>
<td style="text-align: right;">14.5614</td>
<td style="text-align: right;">25.2958</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="confidence-interval-vs.-prediction-interval" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-vs.-prediction-interval">4.3 Confidence Interval vs.&nbsp;Prediction Interval</h2>
<p>It is critical to distinguish between two types of prediction intervals:</p>
<ol type="1">
<li><p><strong>Confidence Interval (CI):</strong> Reflects uncertainty in estimating the <strong>average outcome</strong> <span class="math inline">\(E[Y \mid X_{\text{new}}]\)</span> across all vehicles with the specified characteristics. Its variance depends solely on parameter estimation error <span class="math inline">\(\text{Var}(\hat{\boldsymbol{\beta}})\)</span>.</p></li>
<li><p><strong>Prediction Interval (PI):</strong> Reflects uncertainty in predicting a <strong>single specific vehicle’s outcome</strong> <span class="math inline">\(Y_{\text{new}} = E[Y \mid X_{\text{new}}] + \varepsilon_{\text{new}}\)</span>. Its variance includes both parameter estimation error AND the variance of the random error term <span class="math inline">\(\sigma^2\)</span>:</p>
<p><span class="math display">\[\text{Var}(Y_{\text{new}} - \hat{Y}_{\text{new}}) = \text{Var}(\hat{Y}_{\text{new}}) + \sigma^2\]</span></p></li>
</ol>
<blockquote class="blockquote">
<p><strong>Rule of Thumb:</strong> A <strong>Prediction Interval is always wider than a Confidence Interval</strong> for the same inputs, because predicting an individual observation involves inherent stochastic noise (<span class="math inline">\(\sigma^2\)</span>).</p>
</blockquote>
<p>Let us visualize confidence bands vs.&nbsp;prediction bands across a range of vehicle weights:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate sequence of weights</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>wt_seq <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">wt =</span> <span class="fu">seq</span>(<span class="fl">1.5</span>, <span class="fl">5.5</span>, <span class="at">length.out =</span> <span class="dv">100</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtain predictions with bivariate model for clear visualization</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>conf_bands <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_bivar, <span class="at">newdata =</span> wt_seq, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>pred_bands <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_bivar, <span class="at">newdata =</span> wt_seq, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">wt =</span> wt_seq<span class="sc">$</span>wt,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit =</span> conf_bands[, <span class="st">"fit"</span>],</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf_lwr =</span> conf_bands[, <span class="st">"lwr"</span>],</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">conf_upr =</span> conf_bands[, <span class="st">"upr"</span>],</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred_lwr =</span> pred_bands[, <span class="st">"lwr"</span>],</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred_upr =</span> pred_bands[, <span class="st">"upr"</span>]</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Raw data points</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> mtcars, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> mpg), <span class="at">color =</span> <span class="st">"#2c3e50"</span>, <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Prediction interval ribbon (outer, wider)</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> plot_data, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">ymin =</span> pred_lwr, <span class="at">ymax =</span> pred_upr), </span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">"#e74c3c"</span>, <span class="at">alpha =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Confidence interval ribbon (inner, narrower)</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> plot_data, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">ymin =</span> conf_lwr, <span class="at">ymax =</span> conf_upr), </span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>              <span class="at">fill =</span> <span class="st">"#2980b9"</span>, <span class="at">alpha =</span> <span class="fl">0.35</span>) <span class="sc">+</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Regression line</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> plot_data, <span class="fu">aes</span>(<span class="at">x =</span> wt, <span class="at">y =</span> fit), <span class="at">color =</span> <span class="st">"#16a085"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Confidence Interval vs. Prediction Interval"</span>,</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Inner Blue Band = 95% Confidence Interval (Mean) | Outer Red Band = 95% Prediction Interval (Individual)"</span>,</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Vehicle Weight (1,000 lbs)"</span>,</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Miles Per Gallon (mpg)"</span></span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>, <span class="at">color =</span> <span class="st">"#2c3e50"</span>),</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">color =</span> <span class="st">"#d6dbdf"</span>, <span class="at">fill =</span> <span class="cn">NA</span>)</span>
<span id="cb8-39"><a href="#cb8-39" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Comparison of 95% Confidence Bands (Narrow) vs.&nbsp;95% Prediction Bands (Wide) in Linear Regression.</figcaption>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="model-diagnostics-validation" class="level1">
<h1>5. Model Diagnostics &amp; Validation</h1>
<p>Before relying on OLS linear regression results for inference or policy decisions, researchers must validate that the underlying Gauss-Markov assumptions hold.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_mlr, <span class="at">col =</span> <span class="st">"#2c3e50"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="864"></p>
<figcaption>Diagnostic plots for checking classical linear regression model assumptions.</figcaption>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="diagnostic-checklist-for-researchers" class="level3">
<h3 class="anchored" data-anchor-id="diagnostic-checklist-for-researchers">Diagnostic Checklist for Researchers</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Diagnostic Plot</th>
<th style="text-align: left;">What it Evaluates</th>
<th style="text-align: left;">Ideal Pattern</th>
<th style="text-align: left;">Common Violation &amp; Solution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Residuals vs Fitted</strong></td>
<td style="text-align: left;">Linearity &amp; Homoscedasticity</td>
<td style="text-align: left;">Random scatter around horizontal zero line with constant vertical spread.</td>
<td style="text-align: left;">Curved pattern indicates non-linearity <span class="math inline">\(\to\)</span> apply log/polynomial transforms. Funnel shape indicates heteroscedasticity <span class="math inline">\(\to\)</span> use robust standard errors (e.g.&nbsp;HC3).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Normal Q-Q</strong></td>
<td style="text-align: left;">Normality of Residuals</td>
<td style="text-align: left;">Points closely align along the diagonal dashed 45° reference line.</td>
<td style="text-align: left;">S-curve or heavy tails <span class="math inline">\(\to\)</span> check for extreme values or use non-parametric/bootstrapped inference.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Scale-Location</strong></td>
<td style="text-align: left;">Constant Residual Variance</td>
<td style="text-align: left;">Flat horizontal trendline with equally spread points.</td>
<td style="text-align: left;">Upward/downward slope confirms heteroscedasticity.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Residuals vs Leverage</strong></td>
<td style="text-align: left;">Influential Outliers</td>
<td style="text-align: left;">No observations beyond Cook’s Distance dashed boundaries (<span class="math inline">\(D &gt; 0.5\)</span>).</td>
<td style="text-align: left;">Points in top-right or bottom-right corners exert disproportionate influence <span class="math inline">\(\to\)</span> investigate data anomalies.</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="summary-reference-table" class="level1">
<h1>6. Summary Reference Table</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric / Term</th>
<th style="text-align: left;">Formula</th>
<th style="text-align: left;">Definition / Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Population Regression Function</strong></td>
<td style="text-align: left;"><span class="math inline">\(Y_i = \beta_0 + \beta_1 X_i + \varepsilon_i\)</span></td>
<td style="text-align: left;">Theoretical model linking <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> in the population with stochastic error <span class="math inline">\(\varepsilon_i\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>OLS Slope Estimator (<span class="math inline">\(\hat{\beta}_1\)</span>)</strong></td>
<td style="text-align: left;"><span class="math inline">\(\frac{\sum(X_i-\bar{X})(Y_i-\bar{Y})}{\sum(X_i-\bar{X})^2}\)</span></td>
<td style="text-align: left;">Estimated marginal change in <span class="math inline">\(Y\)</span> per 1-unit change in <span class="math inline">\(X\)</span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Total Sum of Squares (SST)</strong></td>
<td style="text-align: left;"><span class="math inline">\(\sum (Y_i - \bar{Y})^2\)</span></td>
<td style="text-align: left;">Total sample variation in the outcome variable <span class="math inline">\(Y\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Coefficient of Determination (<span class="math inline">\(R^2\)</span>)</strong></td>
<td style="text-align: left;"><span class="math inline">\(1 - \frac{\text{SSE}}{\text{SST}}\)</span></td>
<td style="text-align: left;">Proportion of total variance in <span class="math inline">\(Y\)</span> explained by predictors (<span class="math inline">\(0 \le R^2 \le 1\)</span>).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Adjusted <span class="math inline">\(R^2\)</span> (<span class="math inline">\(\bar{R}^2\)</span>)</strong></td>
<td style="text-align: left;"><span class="math inline">\(1 - (1-R^2)\frac{n-1}{n-k-1}\)</span></td>
<td style="text-align: left;">Goodness-of-fit metric penalizing non-informative added predictors.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong><span class="math inline">\(t\)</span>-Test Statistic</strong></td>
<td style="text-align: left;"><span class="math inline">\(\frac{\hat{\beta}_j - 0}{\text{SE}(\hat{\beta}_j)}\)</span></td>
<td style="text-align: left;">Evaluates individual statistical significance of predictor <span class="math inline">\(X_j\)</span>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong><span class="math inline">\(F\)</span>-Test Statistic</strong></td>
<td style="text-align: left;"><span class="math inline">\(\frac{\text{SSR}/k}{\text{SSE}/(n-k-1)}\)</span></td>
<td style="text-align: left;">Evaluates joint statistical significance of all <span class="math inline">\(k\)</span> slope parameters.</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/adsheilbronn\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>